/**
 * 📊 Meta Engagement Poller
 *
 * Fonctions Inngest pour :
 * 1. Polling périodique de l'engagement sur les posts IG/FB (cron 15 min)
 * 2. Traitement des webhooks Meta (événements temps réel)
 * 3. Auto-génération de DM pour les nouvelles interactions
 */

import { inngest } from "../client";
import { prisma } from "@/lib/prisma";
import { metaGet } from "@/lib/services/meta/graph-api";
import { refreshTokenIfNeeded } from "@/lib/services/meta/token-manager";
import {
  importInteractions,
  generatePersonalizedDM,
  type RawInteraction,
  type SocialPlatform,
} from "@/lib/services/social/prospector";

// ═══════════════════════════════════════════════════════════════════════════
// 1️⃣ POLLING PÉRIODIQUE
// ═══════════════════════════════════════════════════════════════════════════

export const pollMetaEngagement = inngest.createFunction(
  {
    id: "meta-engagement-poller",
    name: "Poll Meta Engagement",
    concurrency: { limit: 1 },
  },
  { cron: "*/15 * * * *" }, // Toutes les 15 minutes
  async ({ step }) => {
    // Trouver tous les comptes Meta actifs
    const accounts = await step.run("find-active-accounts", async () => {
      return prisma.metaSocialAccount.findMany({
        where: { isActive: true },
        select: {
          id: true,
          workspaceId: true,
          facebookPageId: true,
          instagramAccountId: true,
          autoGenerateDMs: true,
        },
      });
    });

    let totalNewInteractions = 0;

    for (const account of accounts) {
      const newInteractionIds = await step.run(
        `poll-account-${account.id}`,
        async () => {
          try {
            const pageToken = await refreshTokenIfNeeded(account.id);
            const ids: string[] = [];

            // Fetch les posts récents de la page IG (dernières 24h)
            if (account.instagramAccountId) {
              const media = await metaGet<{
                data: Array<{ id: string; timestamp: string; permalink?: string }>;
              }>(`/${account.instagramAccountId}/media`, pageToken, {
                fields: "id,timestamp,permalink",
                limit: "10",
              });

              for (const post of media.data || []) {
                // Fetch commentaires de chaque post
                try {
                  const comments = await metaGet<{
                    data: Array<{
                      id: string;
                      text: string;
                      username?: string;
                      from?: { id: string; name: string };
                      timestamp: string;
                    }>;
                  }>(`/${post.id}/comments`, pageToken, {
                    fields: "id,text,username,from,timestamp",
                  });

                  const interactions: RawInteraction[] = (comments.data || []).map((c) => ({
                    platform: "INSTAGRAM" as SocialPlatform,
                    type: "COMMENT" as const,
                    sourceUrl: post.permalink || `https://instagram.com/p/${post.id}`,
                    prospectName: c.from?.name || c.username || "Utilisateur",
                    prospectHandle: c.username ? `@${c.username}` : c.from?.id || "unknown",
                    interactionText: c.text,
                    metaUserId: c.from?.id,
                    metaCommentId: c.id,
                  }));

                  const result = await importInteractions(account.workspaceId, interactions);

                  // Récupérer les IDs des nouvelles interactions importées
                  if (result.imported > 0) {
                    const recent = await prisma.socialInteraction.findMany({
                      where: {
                        workspaceId: account.workspaceId,
                        dmApprovalStatus: "NONE",
                      },
                      orderBy: { createdAt: "desc" },
                      take: result.imported,
                      select: { id: true },
                    });
                    ids.push(...recent.map((r) => r.id));
                  }
                } catch (e) {
                  console.error(`Error fetching comments for post ${post.id}:`, e);
                }
              }
            }

            return ids;
          } catch (error) {
            console.error(`Error polling account ${account.id}:`, error);
            return [];
          }
        }
      );

      totalNewInteractions += newInteractionIds.length;

      // Auto-générer les DM si activé et s'il y a de nouvelles interactions
      if (account.autoGenerateDMs && newInteractionIds.length > 0) {
        await step.run(`auto-generate-dms-${account.id}`, async () => {
          await inngest.send({
            name: "meta/new-interactions",
            data: {
              workspaceId: account.workspaceId,
              interactionIds: newInteractionIds,
            },
          });
        });
      }
    }

    return { accountsPolled: accounts.length, newInteractions: totalNewInteractions };
  }
);

// ═══════════════════════════════════════════════════════════════════════════
// 2️⃣ AUTO-GÉNÉRATION DE DM
// ═══════════════════════════════════════════════════════════════════════════

export const autoGenerateDMs = inngest.createFunction(
  {
    id: "meta-auto-generate-dms",
    name: "Auto-Generate DMs for New Interactions",
    retries: 2,
    concurrency: { limit: 2 },
  },
  { event: "meta/new-interactions" },
  async ({ event, step }) => {
    const { workspaceId, interactionIds } = event.data as {
      workspaceId: string;
      interactionIds: string[];
    };

    let generated = 0;

    for (const id of interactionIds) {
      await step.run(`generate-dm-${id}`, async () => {
        try {
          await generatePersonalizedDM(id);

          // Mettre en attente d'approbation avec la première variante sélectionnée par défaut
          await prisma.socialInteraction.update({
            where: { id },
            data: {
              dmApprovalStatus: "PENDING_APPROVAL",
              selectedDmIndex: 0,
            },
          });

          generated++;
        } catch (error) {
          console.error(`Error generating DM for interaction ${id}:`, error);
        }
      });
    }

    return { workspaceId, generated, total: interactionIds.length };
  }
);

// ═══════════════════════════════════════════════════════════════════════════
// 3️⃣ TRAITEMENT WEBHOOK
// ═══════════════════════════════════════════════════════════════════════════

export const processMetaWebhook = inngest.createFunction(
  {
    id: "meta-webhook-processor",
    name: "Process Meta Webhook Events",
    retries: 1,
  },
  { event: "meta/webhook.received" },
  async ({ event, step }) => {
    const { object, entries } = event.data as {
      object: string;
      entries: Array<{
        id: string;
        time: number;
        changes?: Array<{
          field: string;
          value: Record<string, unknown>;
        }>;
      }>;
    };

    let processed = 0;

    for (const entry of entries) {
      await step.run(`process-entry-${entry.id}-${entry.time}`, async () => {
        // Trouver le MetaSocialAccount correspondant à cette Page/IG account
        const metaAccount = await prisma.metaSocialAccount.findFirst({
          where: {
            OR: [
              { facebookPageId: entry.id },
              { instagramAccountId: entry.id },
            ],
            isActive: true,
          },
        });

        if (!metaAccount) {
          console.log(`No MetaSocialAccount found for entry ${entry.id}`);
          return;
        }

        for (const change of entry.changes || []) {
          if (change.field === "comments" || change.field === "feed") {
            const value = change.value as {
              item?: string;
              comment_id?: string;
              from?: { id: string; name: string };
              message?: string;
              post_id?: string;
            };

            if (value.comment_id && value.from) {
              const platform: SocialPlatform =
                object === "instagram" ? "INSTAGRAM" : "FACEBOOK";

              const interactions: RawInteraction[] = [
                {
                  platform,
                  type: "COMMENT",
                  sourceUrl: value.post_id || "",
                  prospectName: value.from.name,
                  prospectHandle: value.from.id,
                  interactionText: value.message,
                  metaUserId: value.from.id,
                  metaCommentId: value.comment_id,
                },
              ];

              const result = await importInteractions(
                metaAccount.workspaceId,
                interactions
              );

              if (result.imported > 0 && metaAccount.autoGenerateDMs) {
                // Récupérer l'ID de la nouvelle interaction
                const newInteraction = await prisma.socialInteraction.findFirst({
                  where: {
                    workspaceId: metaAccount.workspaceId,
                    metaCommentId: value.comment_id,
                  },
                  select: { id: true },
                });

                if (newInteraction) {
                  await inngest.send({
                    name: "meta/new-interactions",
                    data: {
                      workspaceId: metaAccount.workspaceId,
                      interactionIds: [newInteraction.id],
                    },
                  });
                }
              }

              processed++;
            }
          }
        }
      });
    }

    return { object, entriesCount: entries.length, processed };
  }
);
