"use client";

import { useState, useEffect, useCallback } from "react";
import { getUserWorkspace } from "@/actions/leads";
import {
  trackPostEngagementAction,
  getInteractionsAction,
  generateDMAction,
  regenerateDMAction,
  markAsContactedAction,
  markAsIgnoredAction,
  deleteInteractionAction,
  importInteractionsAction,
  getIGDmQuotaAction,
} from "@/actions/social-prospector";
import {
  getApprovalQueueAction,
  approveDMAction,
  approveWithEditAction,
  rejectDMAction,
  batchApproveDMsAction,
  submitForApprovalAction,
  getSentDMsAction,
} from "@/actions/dm-approval";
import {
  getMetaConnectionStatus,
  listUserPagesAction,
  connectPageAction,
  disconnectPageAction,
  toggleAutoGenerateAction,
} from "@/actions/meta-connection";
import {
  listFacebookGroupsAction,
  getGroupMembersAction,
  generateExtensionTokenAction,
  deleteFacebookGroupAction,
  triggerColdDMBatchAction,
} from "@/actions/facebook-groups";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import { signIn } from "next-auth/react";
import {
  MessageCircle,
  Heart,
  UserPlus,
  Loader2,
  Sparkles,
  Copy,
  ExternalLink,
  RefreshCw,
  Check,
  X,
  MoreVertical,
  Trash2,
  Instagram,
  Facebook,
  Search,
  Upload,
  Eye,
  EyeOff,
  Users,
  Clock,
  CheckCircle2,
  Send,
  AlertCircle,
  Plug,
  Shield,
  Edit3,
  CheckSquare,
  XCircle,
  Inbox,
  ArrowRight,
  UsersRound,
  Key,
  Download,
} from "lucide-react";
import type { SocialPlatform, RawInteraction } from "@/lib/services/social/prospector";

// ═══════════════════════════════════════════════════════════════════════════
// 📌 TYPES
// ═══════════════════════════════════════════════════════════════════════════

interface Interaction {
  id: string;
  platform: string;
  type: string;
  sourceUrl: string;
  prospectName: string;
  prospectHandle: string;
  profileUrl: string | null;
  interactionText: string | null;
  suggestedDMs: DMVariant[] | null;
  status: string;
  dmApprovalStatus: string;
  selectedDmIndex: number | null;
  customDmText: string | null;
  sentAt: string | null;
  sentVia: string | null;
  errorMessage: string | null;
  metaCommentId: string | null;
  metaUserId: string | null;
  createdAt: string;
}

interface DMVariant {
  label: string;
  message: string;
}

interface Stats {
  PENDING: number;
  CONTACTED: number;
  IGNORED: number;
}

interface MetaAccount {
  id: string;
  facebookPageName: string;
  instagramUsername: string | null;
  isActive: boolean;
  autoGenerateDMs: boolean;
  tokenExpiresAt: string | null;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🎨 HELPERS
// ═══════════════════════════════════════════════════════════════════════════

const statusConfig: Record<string, { label: string; color: string; icon: React.ElementType }> = {
  PENDING: { label: "En attente", color: "bg-amber-500/20 text-amber-600 border-amber-500/30", icon: Clock },
  CONTACTED: { label: "Contacté", color: "bg-green-500/20 text-green-600 border-green-500/30", icon: CheckCircle2 },
  IGNORED: { label: "Ignoré", color: "bg-gray-500/20 text-gray-500 border-gray-500/30", icon: EyeOff },
};

const dmStatusConfig: Record<string, { label: string; color: string; icon: React.ElementType }> = {
  NONE: { label: "Pas de DM", color: "bg-gray-100 text-gray-500", icon: MessageCircle },
  PENDING_APPROVAL: { label: "En attente", color: "bg-amber-100 text-amber-700", icon: Clock },
  APPROVED: { label: "Approuvé", color: "bg-blue-100 text-blue-700", icon: CheckSquare },
  REJECTED: { label: "Rejeté", color: "bg-red-100 text-red-700", icon: XCircle },
  SENT: { label: "Envoyé", color: "bg-green-100 text-green-700", icon: Send },
  FAILED: { label: "Échoué", color: "bg-red-100 text-red-700", icon: AlertCircle },
  MANUAL: { label: "Manuel", color: "bg-violet-100 text-violet-700", icon: ExternalLink },
};

const typeIcons: Record<string, React.ElementType> = {
  LIKE: Heart,
  COMMENT: MessageCircle,
  FOLLOW: UserPlus,
};

const platformIcons: Record<string, React.ElementType> = {
  INSTAGRAM: Instagram,
  FACEBOOK: Facebook,
};

// ═══════════════════════════════════════════════════════════════════════════
// 🧱 ONGLET 1 : PROSPECTS
// ═══════════════════════════════════════════════════════════════════════════

function ProspectsTab({ workspaceId }: { workspaceId: string }) {
  const [interactions, setInteractions] = useState<Interaction[]>([]);
  const [stats, setStats] = useState<Stats>({ PENDING: 0, CONTACTED: 0, IGNORED: 0 });
  const [loading, setLoading] = useState(true);
  const [filterStatus, setFilterStatus] = useState("ALL");
  const [filterPlatform, setFilterPlatform] = useState("ALL");
  const [showImport, setShowImport] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    const result = await getInteractionsAction(workspaceId);
    if (result.success && result.data) {
      setInteractions(result.data.interactions as unknown as Interaction[]);
      setStats(result.data.stats as Stats);
    }
    setLoading(false);
  }, [workspaceId]);

  useEffect(() => { load(); }, [load]);

  const filtered = interactions.filter((i) => {
    if (filterStatus !== "ALL" && i.status !== filterStatus) return false;
    if (filterPlatform !== "ALL" && i.platform !== filterPlatform) return false;
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: "En attente", value: stats.PENDING, icon: Clock, color: "amber" },
          { label: "Contactés", value: stats.CONTACTED, icon: CheckCircle2, color: "green" },
          { label: "Total", value: stats.PENDING + stats.CONTACTED + stats.IGNORED, icon: Users, color: "gray" },
        ].map((s) => (
          <Card key={s.label} className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
            <CardContent className="p-4 flex items-center gap-3">
              <div className={`p-2.5 rounded-xl bg-${s.color}-50 border border-${s.color}-200/40`}>
                <s.icon className={`h-5 w-5 text-${s.color}-500`} />
              </div>
              <div>
                <p className="text-2xl font-bold text-gray-900">{s.value}</p>
                <p className="text-xs text-gray-500">{s.label}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Tracker */}
      <PostTracker workspaceId={workspaceId} onTrack={load} />

      {/* Filtres */}
      <div className="flex items-center gap-3">
        <Select value={filterStatus} onValueChange={setFilterStatus}>
          <SelectTrigger className="w-[160px] bg-white/60 border-gray-200"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="ALL">Tous les statuts</SelectItem>
            <SelectItem value="PENDING">En attente</SelectItem>
            <SelectItem value="CONTACTED">Contactés</SelectItem>
            <SelectItem value="IGNORED">Ignorés</SelectItem>
          </SelectContent>
        </Select>
        <Select value={filterPlatform} onValueChange={setFilterPlatform}>
          <SelectTrigger className="w-[160px] bg-white/60 border-gray-200"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="ALL">Toutes</SelectItem>
            <SelectItem value="INSTAGRAM">Instagram</SelectItem>
            <SelectItem value="FACEBOOK">Facebook</SelectItem>
          </SelectContent>
        </Select>
        <Button variant="ghost" size="sm" onClick={load} className="text-gray-500">
          <RefreshCw className="h-4 w-4 mr-1" /> Actualiser
        </Button>
        <Button variant="outline" size="sm" onClick={() => setShowImport(true)} className="ml-auto">
          <Upload className="h-4 w-4 mr-1" /> Import CSV
        </Button>
        <IGExtractorHelp workspaceId={workspaceId} onImport={load} />
      </div>

      {/* Liste */}
      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="h-8 w-8 animate-spin text-emerald-400" />
        </div>
      ) : filtered.length === 0 ? (
        <EmptyState message="Aucune interaction trouvée" cta="Tracker un post" onCta={() => {}} />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {filtered.map((i) => (
            <ProspectCard key={i.id} interaction={i} workspaceId={workspaceId} onUpdate={load} />
          ))}
        </div>
      )}

      <CSVImporter workspaceId={workspaceId} open={showImport} onClose={() => setShowImport(false)} onImport={load} />
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// 🧱 ONGLET 2 : QUEUE D'APPROBATION
// ═══════════════════════════════════════════════════════════════════════════

function ApprovalQueueTab({ workspaceId }: { workspaceId: string }) {
  const [pending, setPending] = useState<Interaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editText, setEditText] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    const result = await getApprovalQueueAction(workspaceId);
    if (result.success && result.data) {
      setPending(result.data.pending as unknown as Interaction[]);
    }
    setLoading(false);
  }, [workspaceId]);

  useEffect(() => { load(); }, [load]);

  async function handleApprove(id: string) {
    const res = await approveDMAction(workspaceId, id);
    if (res.success) { toast.success("DM approuvé !"); load(); }
    else toast.error(res.error || "Erreur");
  }

  async function handleReject(id: string) {
    const res = await rejectDMAction(workspaceId, id);
    if (res.success) { toast.success("DM rejeté"); load(); }
    else toast.error(res.error || "Erreur");
  }

  async function handleApproveWithEdit(id: string) {
    if (!editText.trim()) return;
    const res = await approveWithEditAction(workspaceId, id, editText);
    if (res.success) { toast.success("DM modifié et approuvé !"); setEditingId(null); setEditText(""); load(); }
    else toast.error(res.error || "Erreur");
  }

  async function handleBatchApprove() {
    if (selected.size === 0) return;
    const res = await batchApproveDMsAction(workspaceId, Array.from(selected));
    if (res.success) { toast.success(`${selected.size} DM approuvés !`); setSelected(new Set()); load(); }
    else toast.error(res.error || "Erreur");
  }

  function toggleSelect(id: string) {
    const s = new Set(selected);
    s.has(id) ? s.delete(id) : s.add(id);
    setSelected(s);
  }

  function selectAll() {
    setSelected(new Set(pending.map((p) => p.id)));
  }

  function getDMPreview(interaction: Interaction): string {
    const dms = interaction.suggestedDMs;
    if (!dms || dms.length === 0) return "Pas de DM généré";
    const idx = interaction.selectedDmIndex ?? 0;
    return dms[idx]?.message || dms[0]?.message || "Pas de DM";
  }

  if (loading) return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-emerald-400" /></div>;

  if (pending.length === 0) {
    return <EmptyState message="Aucun DM en attente d'approbation" cta="Voir les prospects" onCta={() => {}} />;
  }

  return (
    <div className="space-y-4">
      {/* Barre d'actions batch */}
      <div className="flex items-center justify-between p-3 bg-white/60 backdrop-blur-sm rounded-lg border border-gray-200/60">
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={selectAll}>
            <CheckSquare className="h-4 w-4 mr-1" /> Tout sélectionner
          </Button>
          <span className="text-sm text-gray-500">{selected.size} sélectionné(s) sur {pending.length}</span>
        </div>
        <Button
          onClick={handleBatchApprove}
          disabled={selected.size === 0}
          size="sm"
          className="bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white"
        >
          <Check className="h-4 w-4 mr-1" /> Approuver la sélection
        </Button>
      </div>

      {/* Liste des DM en attente */}
      <div className="space-y-3">
        {pending.map((interaction) => {
          const TypeIcon = typeIcons[interaction.type] || MessageCircle;
          const PlatformIcon = platformIcons[interaction.platform] || Instagram;
          const isEditing = editingId === interaction.id;

          return (
            <Card key={interaction.id} className={`bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60 ${selected.has(interaction.id) ? "ring-2 ring-emerald-500" : ""}`}>
              <CardContent className="p-4">
                <div className="flex items-start gap-4">
                  {/* Checkbox */}
                  <input
                    type="checkbox"
                    checked={selected.has(interaction.id)}
                    onChange={() => toggleSelect(interaction.id)}
                    className="mt-1 h-4 w-4 rounded border-gray-300 text-emerald-600 focus:ring-emerald-500"
                  />

                  {/* Avatar */}
                  <div className="h-10 w-10 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center text-white font-bold text-sm shrink-0">
                    {interaction.prospectName.split(" ").map((n) => n[0]).join("").slice(0, 2).toUpperCase()}
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className="font-semibold text-gray-900 text-sm">{interaction.prospectName}</h4>
                      <PlatformIcon className="h-3.5 w-3.5 text-gray-400" />
                      <TypeIcon className="h-3.5 w-3.5 text-gray-400" />
                    </div>
                    {interaction.interactionText && (
                      <p className="text-xs text-gray-500 italic mb-2 truncate">&ldquo;{interaction.interactionText}&rdquo;</p>
                    )}

                    {/* DM Preview */}
                    {isEditing ? (
                      <div className="space-y-2">
                        <textarea
                          value={editText}
                          onChange={(e) => setEditText(e.target.value)}
                          rows={3}
                          className="w-full p-2 border border-gray-200 rounded-lg text-sm focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                        />
                        <div className="flex gap-2">
                          <Button size="sm" onClick={() => handleApproveWithEdit(interaction.id)} className="bg-emerald-600 hover:bg-emerald-700 text-white">
                            <Check className="h-3 w-3 mr-1" /> Approuver
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => { setEditingId(null); setEditText(""); }}>
                            Annuler
                          </Button>
                        </div>
                      </div>
                    ) : (
                      <div className="p-2 rounded bg-emerald-50/50 border border-emerald-200/30">
                        <p className="text-sm text-gray-700">{getDMPreview(interaction)}</p>
                      </div>
                    )}
                  </div>

                  {/* Actions */}
                  {!isEditing && (
                    <div className="flex items-center gap-1 shrink-0">
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleApprove(interaction.id)}
                        className="h-8 w-8 text-green-600 hover:bg-green-50"
                        title="Approuver"
                      >
                        <Check className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => { setEditingId(interaction.id); setEditText(getDMPreview(interaction)); }}
                        className="h-8 w-8 text-blue-600 hover:bg-blue-50"
                        title="Modifier"
                      >
                        <Edit3 className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleReject(interaction.id)}
                        className="h-8 w-8 text-red-600 hover:bg-red-50"
                        title="Rejeter"
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// 🧱 ONGLET 3 : DM ENVOYÉS
// ═══════════════════════════════════════════════════════════════════════════

function SentDMsTab({ workspaceId }: { workspaceId: string }) {
  const [sent, setSent] = useState<Interaction[]>([]);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    setLoading(true);
    const result = await getSentDMsAction(workspaceId);
    if (result.success && result.data) {
      setSent(result.data.sent as unknown as Interaction[]);
    }
    setLoading(false);
  }, [workspaceId]);

  useEffect(() => { load(); }, [load]);

  const sentCount = sent.filter((s) => s.dmApprovalStatus === "SENT").length;
  const failedCount = sent.filter((s) => s.dmApprovalStatus === "FAILED").length;
  const manualCount = sent.filter((s) => s.dmApprovalStatus === "MANUAL").length;

  if (loading) return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-emerald-400" /></div>;

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-green-50 border border-green-200/40">
              <Send className="h-5 w-5 text-green-500" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{sentCount}</p>
              <p className="text-xs text-gray-500">Envoyés (API)</p>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-violet-50 border border-violet-200/40">
              <ExternalLink className="h-5 w-5 text-violet-500" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{manualCount}</p>
              <p className="text-xs text-gray-500">Manuel</p>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
          <CardContent className="p-4 flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-red-50 border border-red-200/40">
              <AlertCircle className="h-5 w-5 text-red-500" />
            </div>
            <div>
              <p className="text-2xl font-bold text-gray-900">{failedCount}</p>
              <p className="text-xs text-gray-500">Échoués</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Liste */}
      {sent.length === 0 ? (
        <EmptyState message="Aucun DM envoyé pour l'instant" cta="Voir la queue" onCta={() => {}} />
      ) : (
        <div className="space-y-2">
          {sent.map((i) => {
            const dmStatus = dmStatusConfig[i.dmApprovalStatus] || dmStatusConfig.NONE;
            const DmIcon = dmStatus.icon;
            const PlatformIcon = platformIcons[i.platform] || Instagram;

            return (
              <Card key={i.id} className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
                <CardContent className="p-3 flex items-center gap-3">
                  <div className="h-9 w-9 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center text-white font-bold text-xs shrink-0">
                    {i.prospectName.split(" ").map((n) => n[0]).join("").slice(0, 2).toUpperCase()}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-sm text-gray-900">{i.prospectName}</span>
                      <PlatformIcon className="h-3 w-3 text-gray-400" />
                    </div>
                    <p className="text-xs text-gray-500 truncate">
                      {i.sentVia === "PRIVATE_REPLY" ? "Private Reply" : i.sentVia === "SEND_API" ? "Send API" : "Manuel"}
                      {i.sentAt && ` - ${new Date(i.sentAt).toLocaleDateString("fr-FR")}`}
                    </p>
                  </div>
                  <Badge className={`text-xs ${dmStatus.color}`}>
                    <DmIcon className="h-3 w-3 mr-1" />
                    {dmStatus.label}
                  </Badge>
                  {i.dmApprovalStatus === "MANUAL" && i.profileUrl && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        const dms = i.suggestedDMs;
                        const text = i.customDmText || (dms && dms[i.selectedDmIndex ?? 0]?.message) || "";
                        navigator.clipboard.writeText(text);
                        window.open(i.profileUrl!, "_blank");
                        markAsContactedAction(workspaceId, i.id);
                        toast.success("Message copié, profil ouvert !");
                      }}
                      className="text-xs text-emerald-600"
                    >
                      <Copy className="h-3 w-3 mr-1" /> Copier & Ouvrir
                    </Button>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// 🧱 ONGLET 4 : CONNEXION META
// ═══════════════════════════════════════════════════════════════════════════

function MetaConnectionTab({ workspaceId }: { workspaceId: string }) {
  const [connectionStatus, setConnectionStatus] = useState<{
    connected: boolean;
    accounts: MetaAccount[];
    hasFacebookLogin: boolean;
  } | null>(null);
  const [pages, setPages] = useState<Array<{ id: string; name: string; instagramUsername?: string }>>([]);
  const [showPagePicker, setShowPagePicker] = useState(false);
  const [loading, setLoading] = useState(true);
  const [connecting, setConnecting] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    const result = await getMetaConnectionStatus(workspaceId);
    if (result.success && result.data) {
      setConnectionStatus(result.data as { connected: boolean; accounts: MetaAccount[]; hasFacebookLogin: boolean });
    }
    setLoading(false);
  }, [workspaceId]);

  useEffect(() => { load(); }, [load]);

  async function handleConnectFacebook() {
    // Déclencher l'OAuth Facebook via NextAuth
    signIn("facebook", { callbackUrl: `/sales-os/social-prospector` });
  }

  async function handleSelectPage() {
    setConnecting(true);
    const result = await listUserPagesAction();
    if (result.success && result.data) {
      setPages(result.data);
      setShowPagePicker(true);
    } else {
      toast.error(result.error || "Impossible de charger les Pages");
    }
    setConnecting(false);
  }

  async function handleConnectPage(pageId: string, pageName: string) {
    setConnecting(true);
    const result = await connectPageAction(workspaceId, pageId, pageName);
    if (result.success) {
      toast.success(`Page "${pageName}" connectée !${result.data?.instagramUsername ? ` (IG: @${result.data.instagramUsername})` : ""}`);
      setShowPagePicker(false);
      load();
    } else {
      toast.error(result.error || "Erreur de connexion");
    }
    setConnecting(false);
  }

  async function handleDisconnect(accountId: string) {
    const result = await disconnectPageAction(workspaceId, accountId);
    if (result.success) { toast.success("Page déconnectée"); load(); }
    else toast.error(result.error || "Erreur");
  }

  async function handleToggleAutoGenerate(accountId: string, enabled: boolean) {
    const result = await toggleAutoGenerateAction(workspaceId, accountId, enabled);
    if (result.success) {
      toast.success(enabled ? "Auto-génération activée" : "Auto-génération désactivée");
      load();
    }
  }

  if (loading) return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-emerald-400" /></div>;

  return (
    <div className="space-y-6">
      {/* Statut de connexion */}
      <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
        <CardHeader>
          <CardTitle className="text-gray-900 flex items-center gap-2">
            <Plug className="h-5 w-5 text-emerald-500" />
            Connexion Meta
          </CardTitle>
          <CardDescription>
            Connectez votre Page Facebook et votre compte Instagram Business pour activer le tracking en temps réel et l&apos;envoi automatique de DM.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {!connectionStatus?.hasFacebookLogin ? (
            <div className="text-center py-6">
              <Facebook className="h-12 w-12 text-blue-500 mx-auto mb-4" />
              <p className="text-sm text-gray-500 mb-4">
                Connectez-vous avec Facebook pour accéder à vos Pages et comptes Instagram.
              </p>
              <Button
                onClick={handleConnectFacebook}
                className="bg-[#1877F2] hover:bg-[#166FE5] text-white"
              >
                <Facebook className="h-4 w-4 mr-2" />
                Se connecter avec Facebook
              </Button>
            </div>
          ) : !connectionStatus?.connected ? (
            <div className="text-center py-6">
              <CheckCircle2 className="h-12 w-12 text-green-500 mx-auto mb-4" />
              <p className="text-sm text-gray-700 mb-2 font-medium">Facebook connecté !</p>
              <p className="text-sm text-gray-500 mb-4">
                Sélectionnez maintenant la Page Facebook à connecter à ce workspace.
              </p>
              <Button
                onClick={handleSelectPage}
                disabled={connecting}
                className="bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white"
              >
                {connecting ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <ArrowRight className="h-4 w-4 mr-2" />}
                Choisir une Page
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              {connectionStatus.accounts.map((account) => (
                <div key={account.id} className="flex items-center justify-between p-4 rounded-lg border border-gray-200/60 bg-white/40">
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg bg-blue-50">
                      <Facebook className="h-5 w-5 text-blue-500" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-900">{account.facebookPageName}</p>
                      <div className="flex items-center gap-2 text-xs text-gray-500">
                        {account.instagramUsername && (
                          <span className="flex items-center gap-1">
                            <Instagram className="h-3 w-3" />
                            @{account.instagramUsername}
                          </span>
                        )}
                        {account.tokenExpiresAt && (
                          <span>Token expire le {new Date(account.tokenExpiresAt).toLocaleDateString("fr-FR")}</span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-gray-500">Auto-DM</span>
                      <Switch
                        checked={account.autoGenerateDMs}
                        onCheckedChange={(v) => handleToggleAutoGenerate(account.id, v)}
                      />
                    </div>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleDisconnect(account.id)}
                      className="text-red-500 hover:text-red-700 hover:bg-red-50"
                    >
                      <X className="h-4 w-4 mr-1" /> Déconnecter
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Info compliance */}
      <Card className="bg-amber-50/50 border-amber-200/60">
        <CardContent className="p-4 flex items-start gap-3">
          <Shield className="h-5 w-5 text-amber-500 mt-0.5 shrink-0" />
          <div>
            <p className="font-medium text-amber-800 text-sm">Compliance Meta</p>
            <p className="text-xs text-amber-700 mt-1">
              L&apos;API Meta permet d&apos;envoyer des <strong>Private Replies</strong> aux commentaires (fiable et officiel).
              Pour les likes/follows, l&apos;envoi automatique n&apos;est possible que si l&apos;utilisateur a une conversation ouverte.
              Sinon, le mode &ldquo;Copier & Ouvrir&rdquo; est utilisé en fallback.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Dialog Page Picker */}
      <Dialog open={showPagePicker} onOpenChange={setShowPagePicker}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Choisir une Page Facebook</DialogTitle>
            <DialogDescription>
              Sélectionnez la Page à connecter. Si un compte Instagram Business est lié, il sera automatiquement détecté.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-2 max-h-[400px] overflow-y-auto">
            {pages.length === 0 ? (
              <p className="text-sm text-gray-500 text-center py-4">Aucune Page trouvée. Assurez-vous d&apos;être administrateur d&apos;au moins une Page Facebook.</p>
            ) : (
              pages.map((page) => (
                <button
                  key={page.id}
                  onClick={() => handleConnectPage(page.id, page.name)}
                  disabled={connecting}
                  className="w-full text-left p-3 rounded-lg border border-gray-200 hover:border-emerald-500 hover:bg-emerald-50/50 transition-colors"
                >
                  <p className="font-medium text-gray-900">{page.name}</p>
                  {page.instagramUsername && (
                    <p className="text-xs text-gray-500 flex items-center gap-1 mt-1">
                      <Instagram className="h-3 w-3" /> @{page.instagramUsername}
                    </p>
                  )}
                </button>
              ))
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// 🧱 COMPOSANTS RÉUTILISABLES
// ═══════════════════════════════════════════════════════════════════════════

function ProspectCard({ interaction, workspaceId, onUpdate }: { interaction: Interaction; workspaceId: string; onUpdate: () => void }) {
  const [generating, setGenerating] = useState(false);
  const [showDMs, setShowDMs] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [localDMs, setLocalDMs] = useState<DMVariant[] | null>(interaction.suggestedDMs);

  const TypeIcon = typeIcons[interaction.type] || MessageCircle;
  const PlatformIcon = platformIcons[interaction.platform] || Instagram;
  const status = statusConfig[interaction.status] || statusConfig.PENDING;
  const StatusIcon = status.icon;

  async function handleGenerateDM() {
    setGenerating(true);
    const result = await generateDMAction(workspaceId, interaction.id);
    if (result.success && result.data) {
      setLocalDMs(result.data);
      setShowDMs(true);
      toast.success("DM générés !");
    } else toast.error(result.error || "Erreur");
    setGenerating(false);
  }

  async function handleSubmitForApproval(dmIndex: number) {
    const res = await submitForApprovalAction(workspaceId, interaction.id, dmIndex);
    if (res.success) { toast.success("DM soumis pour approbation !"); onUpdate(); }
    else toast.error(res.error || "Erreur");
  }

  function handleCopyAndOpen(dm: DMVariant, index: number) {
    navigator.clipboard.writeText(dm.message);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
    if (interaction.profileUrl) window.open(interaction.profileUrl, "_blank");
    markAsContactedAction(workspaceId, interaction.id).then(onUpdate);
    toast.success("Message copié et profil ouvert !");
  }

  return (
    <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60 hover:shadow-md transition-shadow">
      <CardContent className="p-5">
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-3">
            <div className="h-11 w-11 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center text-white font-bold text-sm shadow-sm">
              {interaction.prospectName.split(" ").map((n) => n[0]).join("").slice(0, 2).toUpperCase()}
            </div>
            <div>
              <h3 className="font-semibold text-gray-900 text-sm">{interaction.prospectName}</h3>
              <p className="text-xs text-gray-500 flex items-center gap-1"><PlatformIcon className="h-3 w-3" />{interaction.prospectHandle}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className={`text-xs ${status.color}`}>
              <StatusIcon className="h-3 w-3 mr-1" />{status.label}
            </Badge>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="h-8 w-8"><MoreVertical className="h-4 w-4 text-gray-400" /></Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => { markAsIgnoredAction(workspaceId, interaction.id).then(onUpdate); toast.success("Ignoré"); }}>
                  <EyeOff className="h-4 w-4 mr-2" />Ignorer
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => { deleteInteractionAction(workspaceId, interaction.id).then(onUpdate); toast.success("Supprimé"); }} className="text-red-600">
                  <Trash2 className="h-4 w-4 mr-2" />Supprimer
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>

        <div className="mb-4 p-3 rounded-lg bg-gray-50/80 border border-gray-100">
          <div className="flex items-center gap-2 mb-1">
            <TypeIcon className="h-3.5 w-3.5 text-gray-400" />
            <span className="text-xs font-medium text-gray-500 uppercase">{interaction.type}</span>
          </div>
          {interaction.interactionText ? (
            <p className="text-sm text-gray-700 italic">&ldquo;{interaction.interactionText}&rdquo;</p>
          ) : (
            <p className="text-xs text-gray-400">Pas de commentaire (like/follow)</p>
          )}
        </div>

        {!localDMs && interaction.status === "PENDING" && (
          <div className="space-y-1">
            {interaction.platform === "INSTAGRAM" && (
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className="text-xs text-gray-500 cursor-help inline-flex items-center gap-1">
                    💡 Méthode des 3 étapes : Pas de lien au 1er message
                  </span>
                </TooltipTrigger>
                <TooltipContent side="top" className="max-w-[280px]">
                  <p className="font-medium mb-1">Bonnes pratiques Instagram</p>
                  <ol className="text-xs space-y-0.5 list-decimal list-inside">
                    <li>Étape 1 : Question ouverte / Compliment (jamais de lien)</li>
                    <li>Étape 2 : Apport de valeur (si la personne répond)</li>
                    <li>Étape 3 : Le lien vers ton SaaS ou un calendrier</li>
                  </ol>
                </TooltipContent>
              </Tooltip>
            )}
            <Button onClick={handleGenerateDM} disabled={generating} className="w-full bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white">
              {generating ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Sparkles className="h-4 w-4 mr-2" />}
              Générer DM
            </Button>
          </div>
        )}

        {localDMs && (
          <div className="space-y-3">
            <button onClick={() => setShowDMs(!showDMs)} className="text-xs font-medium text-emerald-600 hover:text-emerald-700 flex items-center gap-1">
              {showDMs ? <EyeOff className="h-3 w-3" /> : <Eye className="h-3 w-3" />}
              {showDMs ? "Masquer les DM" : "Voir les DM"}
            </button>
            {showDMs && localDMs.map((dm, idx) => (
              <div key={idx} className="p-3 rounded-lg border border-gray-200/60 bg-white/80 space-y-2">
                <div className="flex items-center justify-between">
                  <Badge variant="outline" className="text-xs">{dm.label}</Badge>
                  <div className="flex gap-1">
                    <Button variant="ghost" size="sm" onClick={() => handleSubmitForApproval(idx)} className="h-7 text-xs text-blue-600 hover:bg-blue-50">
                      <Send className="h-3 w-3 mr-1" /> Approuver
                    </Button>
                    <Button variant="ghost" size="sm" onClick={() => handleCopyAndOpen(dm, idx)} className="h-7 text-xs text-emerald-600 hover:bg-emerald-50">
                      {copiedIndex === idx ? <><Check className="h-3 w-3 mr-1" />Copié !</> : <><Copy className="h-3 w-3 mr-1" />Copier<ExternalLink className="h-3 w-3 ml-1" /></>}
                    </Button>
                  </div>
                </div>
                <p className="text-sm text-gray-700 leading-relaxed">{dm.message}</p>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function PostTracker({ workspaceId, onTrack }: { workspaceId: string; onTrack: () => void }) {
  const [postUrl, setPostUrl] = useState("");
  const [platform, setPlatform] = useState<SocialPlatform>("INSTAGRAM");
  const [loading, setLoading] = useState(false);

  async function handleTrack() {
    if (!postUrl.trim()) { toast.error("Entrez l'URL du post"); return; }
    setLoading(true);
    const result = await trackPostEngagementAction(workspaceId, postUrl, platform);
    if (result.success) { toast.success(`${result.data?.count} interactions détectées !`); setPostUrl(""); onTrack(); }
    else toast.error(result.error || "Erreur");
    setLoading(false);
  }

  return (
    <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
      <CardHeader>
        <CardTitle className="text-gray-900 text-lg flex items-center gap-2"><Search className="h-5 w-5 text-emerald-500" />Tracker un post</CardTitle>
        <CardDescription>Collez l&apos;URL d&apos;un post pour détecter les interactions</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex gap-3">
          <Select value={platform} onValueChange={(v) => setPlatform(v as SocialPlatform)}>
            <SelectTrigger className="w-[160px] bg-white/60 border-gray-200"><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="INSTAGRAM"><span className="flex items-center gap-2"><Instagram className="h-4 w-4" />Instagram</span></SelectItem>
              <SelectItem value="FACEBOOK"><span className="flex items-center gap-2"><Facebook className="h-4 w-4" />Facebook</span></SelectItem>
            </SelectContent>
          </Select>
          <Input placeholder="https://instagram.com/p/..." value={postUrl} onChange={(e) => setPostUrl(e.target.value)} className="flex-1 bg-white/60 border-gray-200" />
          <Button onClick={handleTrack} disabled={loading} className="bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white">
            {loading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Search className="h-4 w-4 mr-2" />}Analyser
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function IGExtractorHelp({ workspaceId, onImport }: { workspaceId: string; onImport: () => void }) {
  const [open, setOpen] = useState(false);
  const [token, setToken] = useState<string | null>(null);
  const [loadingToken, setLoadingToken] = useState(false);

  async function handleGetToken() {
    setLoadingToken(true);
    const res = await generateExtensionTokenAction(workspaceId);
    setLoadingToken(false);
    if (res.success && res.data?.token) {
      setToken(res.data.token);
      toast.success("Token copié pour le script IG");
    } else toast.error(res.error || "Erreur");
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <Button variant="outline" size="sm" onClick={() => setOpen(true)}>
        <Instagram className="h-4 w-4 mr-1" /> Import IG (Script)
      </Button>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Import Instagram - Script Extracteur</DialogTitle>
          <DialogDescription>
            Lance le script sur la liste des abonnés d&apos;un concurrent ou sur une page hashtag Instagram.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 text-sm">
          <ol className="list-decimal list-inside space-y-2 text-gray-700">
            <li>Va sur instagram.com/[compte]/followers/ ou instagram.com/explore/tags/[hashtag]</li>
            <li>Scroll pour charger les profils</li>
            <li>F12 → Console</li>
            <li>Colle le script (fichier scripts/ig-extractor.js)</li>
            <li>Remplace TON_DOMAINE et TA_CLE_API puis exécute</li>
          </ol>
          <div className="space-y-2">
            <Button variant="outline" size="sm" onClick={handleGetToken} disabled={loadingToken}>
              {loadingToken ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Key className="h-4 w-4 mr-2" />}
              Générer un token
            </Button>
            {token && (
              <div className="flex items-center gap-2 p-2 bg-gray-50 rounded-lg">
                <Input value={token} readOnly className="font-mono text-xs h-8" />
                <Button size="sm" variant="ghost" onClick={() => { navigator.clipboard.writeText(token); toast.success("Token copié"); }}>
                  <Copy className="h-4 w-4" />
                </Button>
              </div>
            )}
            <p className="text-xs text-gray-500">
              API URL : <code className="bg-gray-100 px-1 rounded">{typeof window !== "undefined" ? window.location.origin : ""}/api/prospects/import</code>
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function CSVImporter({ workspaceId, open, onClose, onImport }: { workspaceId: string; open: boolean; onClose: () => void; onImport: () => void }) {
  const [csvText, setCsvText] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleImport() {
    if (!csvText.trim()) { toast.error("Collez vos données CSV"); return; }
    setLoading(true);
    const lines = csvText.trim().split("\n");
    const interactions: RawInteraction[] = [];
    for (const line of lines.slice(1)) {
      const [platform, type, sourceUrl, name, handle, profileUrl, text] = line.split(",").map((s) => s.trim().replace(/^"|"$/g, ""));
      if (platform && name && handle) {
        interactions.push({
          platform: (platform.toUpperCase() as SocialPlatform) || "INSTAGRAM",
          type: (type?.toUpperCase() as "LIKE" | "COMMENT" | "FOLLOW") || "COMMENT",
          sourceUrl: sourceUrl || "", prospectName: name, prospectHandle: handle,
          profileUrl: profileUrl || undefined, interactionText: text || undefined,
        });
      }
    }
    if (interactions.length === 0) { toast.error("Aucune interaction valide"); setLoading(false); return; }
    const result = await importInteractionsAction(workspaceId, interactions);
    if (result.success) { toast.success(`${result.data?.imported} importées`); setCsvText(""); onClose(); onImport(); }
    else toast.error(result.error || "Erreur");
    setLoading(false);
  }

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Importer des interactions (CSV)</DialogTitle>
          <DialogDescription>Colonnes : platform, type, sourceUrl, prospectName, prospectHandle, profileUrl, interactionText</DialogDescription>
        </DialogHeader>
        <textarea value={csvText} onChange={(e) => setCsvText(e.target.value)} placeholder={`platform,type,sourceUrl,prospectName,prospectHandle,profileUrl,interactionText\nINSTAGRAM,COMMENT,https://instagram.com/p/123,Marie Dupont,@marie.dupont,,Super !`} rows={8} className="w-full p-3 border border-gray-200 rounded-lg text-sm font-mono bg-gray-50 focus:ring-2 focus:ring-emerald-500" />
        <div className="flex justify-end gap-3">
          <Button variant="outline" onClick={onClose}>Annuler</Button>
          <Button onClick={handleImport} disabled={loading} className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white">
            {loading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Upload className="h-4 w-4 mr-2" />}Importer
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function EmptyState({ message, cta, onCta }: { message: string; cta: string; onCta: () => void }) {
  return (
    <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
      <CardContent className="py-16 text-center">
        <Inbox className="h-12 w-12 text-gray-300 mx-auto mb-4" />
        <h3 className="text-lg font-medium text-gray-900 mb-2">{message}</h3>
        <Button onClick={onCta} variant="outline">{cta}</Button>
      </CardContent>
    </Card>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// 🧱 ONGLET GROUPES FACEBOOK
// ═══════════════════════════════════════════════════════════════════════════

function FacebookGroupsTab({ workspaceId }: { workspaceId: string }) {
  const [groups, setGroups] = useState<Array<{ id: string; name: string; url: string; memberCount: number; lastSyncedAt: string | null }>>([]);
  const [selectedGroup, setSelectedGroup] = useState<string | null>(null);
  const [members, setMembers] = useState<Interaction[]>([]);
  const [memberTotal, setMemberTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [tokenGen, setTokenGen] = useState<string | null>(null);
  const [loadingToken, setLoadingToken] = useState(false);
  const [triggeringBatch, setTriggeringBatch] = useState(false);

  const loadGroups = useCallback(async () => {
    const result = await listFacebookGroupsAction(workspaceId);
    if (result.success && result.data) setGroups(result.data);
  }, [workspaceId]);

  useEffect(() => {
    setLoading(true);
    loadGroups().finally(() => setLoading(false));
  }, [loadGroups]);

  useEffect(() => {
    if (!selectedGroup) { setMembers([]); setMemberTotal(0); return; }
    getGroupMembersAction(workspaceId, selectedGroup, { limit: 100 }).then((r) => {
      if (r.success && r.data) {
        setMembers(r.data.members as unknown as Interaction[]);
        setMemberTotal(r.data.total);
      }
    });
  }, [workspaceId, selectedGroup]);

  async function handleGenerateToken() {
    setLoadingToken(true);
    const res = await generateExtensionTokenAction(workspaceId);
    setLoadingToken(false);
    if (res.success && res.data?.token) {
      setTokenGen(res.data.token);
      toast.success("Token généré ! Copiez-le dans l'extension Chrome.");
    } else toast.error(res.error || "Erreur");
  }

  async function handleDeleteGroup(groupId: string) {
    if (!confirm("Supprimer ce groupe et tous ses membres importés ?")) return;
    const res = await deleteFacebookGroupAction(workspaceId, groupId);
    if (res.success) { toast.success("Groupe supprimé"); loadGroups(); setSelectedGroup(null); }
    else toast.error(res.error || "Erreur");
  }

  async function handleTriggerBatch() {
    setTriggeringBatch(true);
    const res = await triggerColdDMBatchAction(workspaceId);
    setTriggeringBatch(false);
    if (res.success) toast.success("Envoi des DM en cours (traitement asynchrone).");
    else toast.error(res.error ?? "Erreur");
  }

  const g = groups.find((x) => x.id === selectedGroup);

  return (
    <div className="space-y-6">
      {/* ToS Warning */}
      <div className="flex gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4">
        <AlertCircle className="h-5 w-5 text-amber-500 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-sm font-semibold text-amber-800">Utilisation responsable — CGU Facebook</p>
          <ul className="text-xs text-amber-700 space-y-1 list-disc list-inside">
            <li>L&apos;extraction de membres sans consentement peut violer les <strong>CGU Facebook (Section 3.2)</strong> et entraîner la suspension de votre compte.</li>
            <li>N&apos;envoyez des DM qu&apos;aux membres avec qui vous avez un lien professionnel légitime et une valeur ajoutée claire.</li>
            <li>Respectez le <strong>RGPD</strong> : les données extraites ne doivent pas être partagées ou revendues.</li>
            <li>Limitez les imports à <strong>50–100 membres/jour</strong> pour éviter les détections automatiques.</li>
          </ul>
        </div>
      </div>

      <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Key className="h-5 w-5" /> Token Extension Chrome
          </CardTitle>
          <CardDescription>
            Génèrez un token pour l&apos;extension Chrome qui scrape les membres des groupes Facebook. Installez l&apos;extension depuis le dossier chrome-extension.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Button onClick={handleGenerateToken} disabled={loadingToken} variant="outline" size="sm">
            {loadingToken ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Download className="h-4 w-4 mr-2" />}
            Générer un token
          </Button>
          {tokenGen && (
            <div className="flex items-center gap-2 p-3 bg-gray-50 rounded-lg">
              <Input value={tokenGen} readOnly className="font-mono text-sm" />
              <Button size="sm" variant="ghost" onClick={() => { navigator.clipboard.writeText(tokenGen); toast.success("Copié"); }}>
                <Copy className="h-4 w-4" />
              </Button>
            </div>
          )}
          <div className="pt-2 border-t">
            <Button onClick={handleTriggerBatch} disabled={triggeringBatch} variant="outline" size="sm">
              {triggeringBatch ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Send className="h-4 w-4 mr-2" />}
              Lancer l&apos;envoi des DM approuvés
            </Button>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60 md:col-span-1">
          <CardHeader>
            <CardTitle>Groupes importés</CardTitle>
            <CardDescription>Groupes dont les membres ont été importés via l&apos;extension</CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex justify-center py-8"><Loader2 className="h-6 w-6 animate-spin text-emerald-500" /></div>
            ) : groups.length === 0 ? (
              <p className="text-sm text-gray-500">Aucun groupe. Utilisez l&apos;extension Chrome sur la page membres d&apos;un groupe Facebook.</p>
            ) : (
              <div className="space-y-2">
                {groups.map((gr) => (
                  <button
                    key={gr.id}
                    onClick={() => setSelectedGroup(gr.id)}
                    className={`w-full text-left p-3 rounded-lg border transition-colors ${selectedGroup === gr.id ? "border-emerald-500 bg-emerald-50" : "border-gray-200 hover:bg-gray-50"}`}
                  >
                    <div className="font-medium truncate">{gr.name}</div>
                    <div className="text-xs text-gray-500">{gr.memberCount} membres</div>
                  </button>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="bg-white/60 backdrop-blur-sm shadow-sm border-gray-200/60 md:col-span-2">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>{g?.name || "Sélectionnez un groupe"}</CardTitle>
              <CardDescription>{g ? `${memberTotal} membres au total` : "—"}</CardDescription>
            </div>
            {g && (
              <Button variant="outline" size="sm" onClick={() => handleDeleteGroup(g.id)} className="text-red-600">
                <Trash2 className="h-4 w-4 mr-1" /> Supprimer
              </Button>
            )}
          </CardHeader>
          <CardContent>
            {!g ? (
              <p className="text-sm text-gray-500">Sélectionnez un groupe pour voir ses membres.</p>
            ) : members.length === 0 ? (
              <p className="text-sm text-gray-500">Chargement...</p>
            ) : (
              <div className="space-y-2 max-h-[400px] overflow-y-auto">
                {members.map((m) => (
                  <ProspectCard
                    key={m.id}
                    interaction={m}
                    workspaceId={workspaceId}
                    onUpdate={() => selectedGroup && getGroupMembersAction(workspaceId, selectedGroup).then((r) => {
                      if (r.success && r.data) {
                        setMembers(r.data.members as unknown as Interaction[]);
                        setMemberTotal(r.data.total);
                      }
                    })}
                  />
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// 🖥️ PAGE PRINCIPALE
// ═══════════════════════════════════════════════════════════════════════════

export default function SocialProspectorPage() {
  const [workspaceId, setWorkspaceId] = useState<string | null>(null);

  useEffect(() => {
    getUserWorkspace().then((result) => {
      if (result.success && result.workspaceId) {
        setWorkspaceId(result.workspaceId);
      }
    });
  }, []);

  if (!workspaceId) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-emerald-400" />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold bg-gradient-to-r from-violet-500 via-fuchsia-500 to-pink-500 bg-clip-text text-transparent flex items-center gap-3">
          <MessageCircle className="h-8 w-8 text-violet-500" />
          Social Prospector
        </h1>
        <p className="text-gray-500 mt-2">
          Convertissez l&apos;engagement social en opportunités commerciales avec des DM personnalisés par l&apos;IA
        </p>
      </div>

      {/* Tabs */}
      <Tabs defaultValue="prospects" className="space-y-6">
        <TabsList className="bg-white/50 backdrop-blur-sm border border-gray-200">
          <TabsTrigger value="prospects" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
            <Users className="h-4 w-4 mr-2" /> Prospects
          </TabsTrigger>
          <TabsTrigger value="approval" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
            <Inbox className="h-4 w-4 mr-2" /> Approbation
          </TabsTrigger>
          <TabsTrigger value="sent" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
            <Send className="h-4 w-4 mr-2" /> DM Envoyés
          </TabsTrigger>
          <TabsTrigger value="connection" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
            <Plug className="h-4 w-4 mr-2" /> Connexion
          </TabsTrigger>
          <TabsTrigger value="groups" className="data-[state=active]:bg-emerald-600 data-[state=active]:text-white">
            <UsersRound className="h-4 w-4 mr-2" /> Groupes Facebook
          </TabsTrigger>
        </TabsList>

        <TabsContent value="prospects">
          <ProspectsTab workspaceId={workspaceId} />
        </TabsContent>

        <TabsContent value="approval">
          <ApprovalQueueTab workspaceId={workspaceId} />
        </TabsContent>

        <TabsContent value="sent">
          <SentDMsTab workspaceId={workspaceId} />
        </TabsContent>

        <TabsContent value="connection">
          <MetaConnectionTab workspaceId={workspaceId} />
        </TabsContent>
        <TabsContent value="groups">
          <FacebookGroupsTab workspaceId={workspaceId} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
