import { generateBulkArticles, generateSingleArticle } from "./functions/bulk-articles";
import {
  sendSequenceStep,
  startSequence,
  trackEmailEvent,
  retryFailedSteps,
} from "./functions/sequence-sender";
import {
  launchCampaignFn,
  scheduleNextCampaignSteps,
} from "./functions/campaign-sender";
import { checkRepliesForAllWorkspaces } from "./functions/reply-checker";
import {
  pollMetaEngagement,
  autoGenerateDMs,
  processMetaWebhook,
} from "./functions/meta-engagement-poller";
import { sendApprovedDMs } from "./functions/meta-dm-sender";
import { generateSocialFactory } from "./functions/social-factory";
import {
  agentBrainDaily,
  agentBrainManualCycle,
  agentBrainExecuteDecisions,
  agentBrainWeeklyLearn,
} from "./functions/agent-brain";
import {
  autoEnrichOnCreate,
  autoEnrichBatchNightly,
} from "./functions/auto-enrich";
import {
  scoreProspectsPeriodic,
  rescoreProspectOnEvent,
} from "./functions/score-prospects";
import { scanCompetitorAlerts } from "./functions/competitor-alerts";
import { scrapeViralPostsCron, scrapeViralPostsManual } from "./functions/viral-monitor";
import { syncGscDataDaily } from "./functions/gsc-sync";
import { warmupDailyScheduler } from "./functions/warmup-scheduler";
import { scheduledPostPublisher } from "./functions/scheduled-publisher";
import { runSuperscaleAd } from "./functions/superscale-ads";
import { syncPostAnalyticsCron, syncPostAnalyticsManual } from "./functions/sync-post-analytics";
import { intentSignalsDailyCron, intentSignalsManual } from "./functions/intent-signals-daily";
import { linkedInReplyChecker, linkedInReplyCheckerManual } from "./functions/linkedin-reply-checker";
import { emailOutreachDaily, emailOutreachManual } from "./functions/email-outreach-daily";
import { csoAgentDaily, csoAgentManual, csoAgentExecute } from "./functions/cso-agent-daily";
import { runPersonaPipeline } from "./functions/persona-pipeline";
import { personaWeeklyLearning, personaLearningManual } from "./functions/persona-learning";
import {
  pollLinkedInEngagement,
  pollLinkedInEngagementManual,
  autoEnrollWarmLeads,
  serverSideWarmLeadsCron,
  serverSideWarmLeadsManual,
} from "./functions/linkedin-engagement-poller";
import { runVideoAdPipeline, videoAdPipelineFailure } from "./functions/video-ads-pipeline";
import { hubspotSyncFunction } from "./functions/hubspot-sync";
import { sequenceOptimizerFunction } from "./functions/sequence-optimizer";
import { inngestFailureMonitor } from "./functions/failure-monitor";

// Export all Inngest functions
export const functions = [
  generateBulkArticles,
  generateSingleArticle,
  sendSequenceStep,
  startSequence,
  trackEmailEvent,
  retryFailedSteps,
  launchCampaignFn,
  scheduleNextCampaignSteps,
  checkRepliesForAllWorkspaces,
  // Meta Social Prospector
  pollMetaEngagement,
  autoGenerateDMs,
  processMetaWebhook,
  sendApprovedDMs,
  // Social Content Factory
  generateSocialFactory,
  // Agent Brain (Cerveau Central)
  agentBrainDaily,
  agentBrainManualCycle,
  agentBrainExecuteDecisions,
  agentBrainWeeklyLearn,
  // Agent Intelligence — Auto-enrichissement prospects
  autoEnrichOnCreate,
  autoEnrichBatchNightly,
  // Agent Intelligence — Scoring dynamique
  scoreProspectsPeriodic,
  rescoreProspectOnEvent,
  // CMO Intelligence — Surveillance concurrents
  scanCompetitorAlerts,
  // CMO Intelligence — Sync Google Search Console
  syncGscDataDaily,
  // Email Deliverability — Warm-up quotidien
  warmupDailyScheduler,
  // Social Calendar — Publication automatique des posts planifiés
  scheduledPostPublisher,
  // Superscale Ad Agent — Pipeline créatif end-to-end
  runSuperscaleAd,
  // Viral Monitor — Veille posts viraux LinkedIn & Twitter
  scrapeViralPostsCron,
  scrapeViralPostsManual,
  // Social Analytics — Sync LinkedIn post metrics
  syncPostAnalyticsCron,
  syncPostAnalyticsManual,
  // CSO Intelligence — Surveillance continue intent signals
  intentSignalsDailyCron,
  intentSignalsManual,
  // CSO LinkedIn — Détection des réponses (toutes les 4h)
  linkedInReplyChecker,
  linkedInReplyCheckerManual,
  // CSO Email — Outreach autonome (envoi quotidien 8h)
  emailOutreachDaily,
  emailOutreachManual,
  // CSO Agent — Pipeline manager semi-auto (analyse 7h + exécution on approve)
  csoAgentDaily,
  csoAgentManual,
  csoAgentExecute,
  // Persona Pipeline — prospection orchestrée par persona
  runPersonaPipeline,
  // Persona Learning — analyse hebdo + suggestions ICP (lundi 8h)
  personaWeeklyLearning,
  personaLearningManual,
  // CSO Warm Leads — extraction engagements LinkedIn + enrôlement séquences
  pollLinkedInEngagement,
  pollLinkedInEngagementManual,
  autoEnrollWarmLeads,
  // CSO Warm Leads — server-side viewers + followers (sans extension ouverte)
  serverSideWarmLeadsCron,
  serverSideWarmLeadsManual,
  // Video Ads UGC — Pipeline Kling AI (image2video + lip-sync)
  runVideoAdPipeline,
  videoAdPipelineFailure,
  // CRM — Sync bidirectionnelle HubSpot (toutes les 30min)
  hubspotSyncFunction,
  // CSO AI — Optimisation automatique des séquences (lundi 8h)
  sequenceOptimizerFunction,
  // Monitoring — capture toutes les erreurs Inngest vers Sentry
  inngestFailureMonitor,
];
