import { generateBulkArticles, generateSingleArticle } from "./functions/bulk-articles";
import {
  sendSequenceStep,
  startSequence,
  trackEmailEvent,
  retryFailedSteps,
} from "./functions/sequence-sender";
import {
  launchCampaignFn,
  scheduleNextCampaignSteps,
} from "./functions/campaign-sender";
import { checkRepliesForAllWorkspaces } from "./functions/reply-checker";
import {
  pollMetaEngagement,
  autoGenerateDMs,
  processMetaWebhook,
} from "./functions/meta-engagement-poller";
import { sendApprovedDMs } from "./functions/meta-dm-sender";
import { processGroupMemberColdDMs } from "./functions/facebook-groups-cold-dm";
import { generateSocialFactory } from "./functions/social-factory";
import {
  agentBrainDaily,
  agentBrainManualCycle,
  agentBrainExecuteDecisions,
  agentBrainWeeklyLearn,
} from "./functions/agent-brain";
import {
  autoEnrichOnCreate,
  autoEnrichBatchNightly,
} from "./functions/auto-enrich";
import {
  scoreProspectsPeriodic,
  rescoreProspectOnEvent,
} from "./functions/score-prospects";
import { scanCompetitorAlerts } from "./functions/competitor-alerts";
import { syncGscDataDaily } from "./functions/gsc-sync";
import { warmupDailyScheduler } from "./functions/warmup-scheduler";
import { scheduledPostPublisher } from "./functions/scheduled-publisher";

// Export all Inngest functions
export const functions = [
  generateBulkArticles,
  generateSingleArticle,
  sendSequenceStep,
  startSequence,
  trackEmailEvent,
  retryFailedSteps,
  launchCampaignFn,
  scheduleNextCampaignSteps,
  checkRepliesForAllWorkspaces,
  // Meta Social Prospector
  pollMetaEngagement,
  autoGenerateDMs,
  processMetaWebhook,
  sendApprovedDMs,
  processGroupMemberColdDMs,
  // Social Content Factory
  generateSocialFactory,
  // Agent Brain (Cerveau Central)
  agentBrainDaily,
  agentBrainManualCycle,
  agentBrainExecuteDecisions,
  agentBrainWeeklyLearn,
  // Agent Intelligence — Auto-enrichissement prospects
  autoEnrichOnCreate,
  autoEnrichBatchNightly,
  // Agent Intelligence — Scoring dynamique
  scoreProspectsPeriodic,
  rescoreProspectOnEvent,
  // CMO Intelligence — Surveillance concurrents
  scanCompetitorAlerts,
  // CMO Intelligence — Sync Google Search Console
  syncGscDataDaily,
  // Email Deliverability — Warm-up quotidien
  warmupDailyScheduler,
  // Social Calendar — Publication automatique des posts planifiés
  scheduledPostPublisher,
];
