"use client";

import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { signIn } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Key,
  Plug,
  Plus,
  Copy,
  Trash2,
  Loader2,
  AlertTriangle,
  Shield,
  ExternalLink,
  CheckCircle2,
  Linkedin,
  Facebook,
  Instagram,
  RefreshCw,
} from "lucide-react";
import {
  createSkalleApiKeyAction,
  listSkalleApiKeysAction,
  revokeSkalleApiKeyAction,
  createExternalIntegrationAction,
  listExternalIntegrationsAction,
  deleteExternalIntegrationAction,
} from "@/actions/integrations-api";
import {
  listUserPagesAction,
  connectPageAction,
  disconnectPageAction,
  getMetaConnectionStatus,
  toggleAutoGenerateAction,
} from "@/actions/meta-connection";
import {
  EXTERNAL_INTEGRATION_PROVIDERS,
  type ExternalIntegrationProvider,
} from "@/lib/constants/integrations";
import { toast } from "sonner";

interface IntegrationsClientProps {
  workspaceId: string;
}

export function IntegrationsClient({ workspaceId }: IntegrationsClientProps) {
  const searchParams = useSearchParams();

  useEffect(() => {
    if (searchParams.get("linkedin") === "connected") {
      toast.success("LinkedIn connecté avec succès !");
    } else if (searchParams.get("linkedin") === "error") {
      toast.error("Erreur lors de la connexion LinkedIn.");
    }
  }, [searchParams]);

  // Meta (Facebook / Instagram) state
  const [metaStatus, setMetaStatus] = useState<{
    connected: boolean;
    hasFacebookLogin: boolean;
    accounts: Array<{
      id: string;
      facebookPageName: string;
      instagramUsername: string | null;
      isActive: boolean;
      autoGenerateDMs: boolean;
      tokenExpiresAt: Date | null;
    }>;
  } | null>(null);
  const [pagesModalOpen, setPagesModalOpen] = useState(false);
  const [facebookPages, setFacebookPages] = useState<Array<{ id: string; name: string; category?: string }>>([]);
  const [pagesLoading, setPagesLoading] = useState(false);
  const [connectingPageId, setConnectingPageId] = useState<string | null>(null);
  const [disconnectMetaId, setDisconnectMetaId] = useState<string | null>(null);
  const [disconnectMetaLoading, setDisconnectMetaLoading] = useState(false);
  const [toggleLoading, setToggleLoading] = useState<string | null>(null);

  const [inboundKeys, setInboundKeys] = useState<
    Array<{ id: string; name: string; keyPrefix: string; lastUsedAt: Date | null; createdAt: Date }>
  >([]);
  const [outboundList, setOutboundList] = useState<
    Array<{ id: string; provider: string; createdAt: Date }>
  >([]);
  const [loading, setLoading] = useState(true);
  const [apiError, setApiError] = useState<string | null>(null);

  // Inbound: create key modal
  const [createKeyOpen, setCreateKeyOpen] = useState(false);
  const [newKeyName, setNewKeyName] = useState("");
  const [createdKey, setCreatedKey] = useState<string | null>(null);
  const [createdKeyPrefix, setCreatedKeyPrefix] = useState<string | null>(null);
  const [createKeyLoading, setCreateKeyLoading] = useState(false);

  // Inbound: revoke confirm
  const [revokeId, setRevokeId] = useState<string | null>(null);
  const [revokeLoading, setRevokeLoading] = useState(false);

  // Outbound: connect modal
  const [connectProvider, setConnectProvider] = useState<ExternalIntegrationProvider | null>(null);
  const [connectApiKey, setConnectApiKey] = useState("");
  const [connectLoading, setConnectLoading] = useState(false);

  // WordPress specific fields
  const [wpSiteUrl, setWpSiteUrl] = useState("");
  const [wpUsername, setWpUsername] = useState("");
  const [wpAppPassword, setWpAppPassword] = useState("");

  // Strapi specific fields
  const [strapiUrl, setStrapiUrl] = useState("");
  const [strapiToken, setStrapiToken] = useState("");
  const [strapiContentType, setStrapiContentType] = useState("articles");

  // Sanity specific fields
  const [sanityProjectId, setSanityProjectId] = useState("");
  const [sanityDataset, setSanityDataset] = useState("production");
  const [sanityToken, setSanityToken] = useState("");
  const [sanityDocType, setSanityDocType] = useState("article");

  // Contentful specific fields
  const [contentfulSpaceId, setContentfulSpaceId] = useState("");
  const [contentfulToken, setContentfulToken] = useState("");
  const [contentfulEnvId, setContentfulEnvId] = useState("master");
  const [contentfulContentTypeId, setContentfulContentTypeId] = useState("blogPost");

  // REST_API specific fields
  const [restApiUrl, setRestApiUrl] = useState("");
  const [restApiToken, setRestApiToken] = useState("");
  const [restApiFieldMap, setRestApiFieldMap] = useState("");

  // Outbound: delete confirm
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);

  const providers = EXTERNAL_INTEGRATION_PROVIDERS;

  const loadData = async () => {
    setLoading(true);
    setApiError(null);
    const [keysRes, intRes, metaRes] = await Promise.all([
      listSkalleApiKeysAction(workspaceId),
      listExternalIntegrationsAction(workspaceId),
      getMetaConnectionStatus(workspaceId),
    ]);
    if (keysRes.success && Array.isArray(keysRes.keys)) setInboundKeys(keysRes.keys);
    else if (keysRes.error) setApiError(keysRes.error);
    if (intRes.success && Array.isArray(intRes.integrations)) setOutboundList(intRes.integrations);
    else if (intRes.error && !keysRes.error) setApiError(intRes.error);
    if (metaRes.success && metaRes.data) setMetaStatus(metaRes.data);
    setLoading(false);
  };

  useEffect(() => {
    loadData();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspaceId]);

  const handleCreateKey = async () => {
    setCreateKeyLoading(true);
    const res = await createSkalleApiKeyAction(newKeyName || "Clé API", workspaceId);
    setCreateKeyLoading(false);
    if (res.success && res.key) {
      setCreatedKey(res.key);
      setCreatedKeyPrefix(res.keyPrefix ?? null);
      setNewKeyName("");
      toast.success("Clé créée. Copiez-la maintenant, elle ne sera plus affichée.");
    } else {
      toast.error(res.error ?? "Erreur lors de la création");
    }
  };

  const handleCloseCreateKeyModal = () => {
    setCreateKeyOpen(false);
    setCreatedKey(null);
    setCreatedKeyPrefix(null);
    setNewKeyName("");
    if (createdKey) loadData();
  };

  const handleCopyKey = () => {
    if (createdKey) {
      navigator.clipboard.writeText(createdKey);
      toast.success("Clé copiée dans le presse-papiers");
    }
  };

  const handleRevoke = async () => {
    if (!revokeId) return;
    setRevokeLoading(true);
    const res = await revokeSkalleApiKeyAction(revokeId, workspaceId);
    setRevokeLoading(false);
    setRevokeId(null);
    if (res.success) {
      toast.success("Clé révoquée");
      loadData();
    } else {
      toast.error(res.error ?? "Erreur");
    }
  };

  const handleConnectOutbound = async () => {
    if (!connectProvider) return;
    setConnectLoading(true);

    // Sérialiser selon le provider
    let apiKeyValue: string;
    if (connectProvider === "WORDPRESS") {
      apiKeyValue = JSON.stringify({ siteUrl: wpSiteUrl, username: wpUsername, applicationPassword: wpAppPassword });
    } else if (connectProvider === "STRAPI") {
      apiKeyValue = JSON.stringify({ url: strapiUrl, token: strapiToken, contentType: strapiContentType || "articles" });
    } else if (connectProvider === "SANITY") {
      apiKeyValue = JSON.stringify({ projectId: sanityProjectId, dataset: sanityDataset || "production", token: sanityToken, documentType: sanityDocType || "article" });
    } else if (connectProvider === "CONTENTFUL") {
      apiKeyValue = JSON.stringify({ spaceId: contentfulSpaceId, accessToken: contentfulToken, environmentId: contentfulEnvId || "master", contentTypeId: contentfulContentTypeId || "blogPost" });
    } else if (connectProvider === "REST_API") {
      let fieldMap: Record<string, string> | undefined;
      if (restApiFieldMap.trim()) {
        try { fieldMap = JSON.parse(restApiFieldMap); } catch { /* ignore invalid JSON */ }
      }
      apiKeyValue = JSON.stringify({ url: restApiUrl, ...(restApiToken && { token: restApiToken }), ...(fieldMap && { fieldMap }) });
    } else {
      apiKeyValue = connectApiKey;
    }

    const res = await createExternalIntegrationAction(connectProvider, apiKeyValue, workspaceId);
    setConnectLoading(false);
    if (res.success) {
      toast.success("Connecteur configuré. La clé est chiffrée et stockée de manière sécurisée.");
      setConnectProvider(null);
      setConnectApiKey("");
      setWpSiteUrl(""); setWpUsername(""); setWpAppPassword("");
      setStrapiUrl(""); setStrapiToken(""); setStrapiContentType("articles");
      setSanityProjectId(""); setSanityDataset("production"); setSanityToken(""); setSanityDocType("article");
      setContentfulSpaceId(""); setContentfulToken(""); setContentfulEnvId("master"); setContentfulContentTypeId("blogPost");
      setRestApiUrl(""); setRestApiToken(""); setRestApiFieldMap("");
      loadData();
    } else {
      toast.error(res.error ?? "Erreur");
    }
  };

  const handleDeleteIntegration = async () => {
    if (!deleteId) return;
    setDeleteLoading(true);
    const res = await deleteExternalIntegrationAction(deleteId, workspaceId);
    setDeleteLoading(false);
    setDeleteId(null);
    if (res.success) {
      toast.success("Intégration supprimée");
      loadData();
    } else {
      toast.error(res.error ?? "Erreur");
    }
  };

  // Auto-open pages modal after Facebook OAuth redirect
  useEffect(() => {
    if (searchParams.get("meta") === "connect" && metaStatus?.hasFacebookLogin && !loading) {
      handleOpenPagesModal();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams, metaStatus, loading]);

  const handleOpenPagesModal = async () => {
    setPagesLoading(true);
    setPagesModalOpen(true);
    const res = await listUserPagesAction();
    setPagesLoading(false);
    if (res.success && res.data) {
      setFacebookPages(res.data);
    } else {
      toast.error(res.error ?? "Erreur lors de la récupération des Pages Facebook");
      setPagesModalOpen(false);
    }
  };

  const handleConnectPage = async (pageId: string, pageName: string) => {
    setConnectingPageId(pageId);
    const res = await connectPageAction(workspaceId, pageId, pageName);
    setConnectingPageId(null);
    if (res.success) {
      const igMsg = res.data?.instagramUsername ? ` + Instagram @${res.data.instagramUsername}` : "";
      toast.success(`Page "${pageName}" connectée${igMsg}`);
      setPagesModalOpen(false);
      loadData();
    } else {
      toast.error(res.error ?? "Erreur lors de la connexion");
    }
  };

  const handleDisconnectMeta = async () => {
    if (!disconnectMetaId) return;
    setDisconnectMetaLoading(true);
    const res = await disconnectPageAction(workspaceId, disconnectMetaId);
    setDisconnectMetaLoading(false);
    setDisconnectMetaId(null);
    if (res.success) {
      toast.success("Page déconnectée");
      loadData();
    } else {
      toast.error(res.error ?? "Erreur");
    }
  };

  const handleToggleAutoGenerate = async (metaAccountId: string, enabled: boolean) => {
    setToggleLoading(metaAccountId);
    const res = await toggleAutoGenerateAction(workspaceId, metaAccountId, enabled);
    setToggleLoading(null);
    if (res.success) {
      // Optimistic update
      setMetaStatus((prev) =>
        prev
          ? {
              ...prev,
              accounts: prev.accounts.map((a) =>
                a.id === metaAccountId ? { ...a, autoGenerateDMs: enabled } : a
              ),
            }
          : prev
      );
    } else {
      toast.error(res.error ?? "Erreur");
    }
  };

  const formatDate = (d: Date | null) =>
    d ? new Date(d).toLocaleDateString("fr-FR", { day: "numeric", month: "short", year: "numeric" }) : "—";

  return (
    <div className="container max-w-4xl py-8">
      <div className="mb-8">
        <h1 className="text-2xl font-semibold tracking-tight">
          Developer & Integration Hub
        </h1>
        <p className="text-muted-foreground mt-1">
          Clés API Skalle (entrée) et connecteurs externes (sortie). Sécurité bancaire.
        </p>
      </div>

      {apiError && (
        <Card className="mb-6 border-amber-500/50 bg-amber-500/5">
          <CardContent className="flex items-center gap-3 pt-6">
            <AlertTriangle className="h-5 w-5 text-amber-600" />
            <div>
              <p className="font-medium text-amber-800 dark:text-amber-200">{apiError}</p>
              <p className="text-sm text-muted-foreground">
                Passez à un plan AGENCY ou SCALE pour activer les intégrations API.
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      <Tabs defaultValue="inbound" className="space-y-6">
        <TabsList className="grid w-full max-w-md grid-cols-2">
          <TabsTrigger value="inbound" className="flex items-center gap-2">
            <Key className="h-4 w-4" />
            API Skalle (Inbound)
          </TabsTrigger>
          <TabsTrigger value="outbound" className="flex items-center gap-2">
            <Plug className="h-4 w-4" />
            Outils connectés (Outbound)
          </TabsTrigger>
        </TabsList>

        <TabsContent value="inbound" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Shield className="h-5 w-5" />
                Clés API Skalle
              </CardTitle>
              <CardDescription>
                Les autres services (Zapier, Make, Typeform) utilisent ces clés pour appeler Skalle.
                Seul le hash est stocké en base — jamais la clé en clair.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <Button
                onClick={() => setCreateKeyOpen(true)}
                disabled={!!apiError}
                className="gap-2"
              >
                <Plus className="h-4 w-4" />
                Créer une nouvelle clé secrète
              </Button>

              {loading ? (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Chargement…
                </div>
              ) : inboundKeys.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  Aucune clé. Créez-en une pour connecter vos outils.
                </p>
              ) : (
                <ul className="divide-y rounded-md border">
                  {inboundKeys.map((k) => (
                    <li
                      key={k.id}
                      className="flex items-center justify-between px-4 py-3"
                    >
                      <div>
                        <p className="font-medium">{k.name}</p>
                        <p className="text-sm text-muted-foreground font-mono">
                          {k.keyPrefix}
                        </p>
                        <p className="text-xs text-muted-foreground mt-0.5">
                          Dernière utilisation : {formatDate(k.lastUsedAt)} · Créée le{" "}
                          {formatDate(k.createdAt)}
                        </p>
                      </div>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="text-destructive hover:text-destructive"
                        onClick={() => setRevokeId(k.id)}
                      >
                        <Trash2 className="h-4 w-4 mr-1" />
                        Révoquer
                      </Button>
                    </li>
                  ))}
                </ul>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="outbound" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Plug className="h-5 w-5" />
                Connecteurs externes
              </CardTitle>
              <CardDescription>
                Vos clés (WordPress, SendGrid, CRM…) sont chiffrées en AES-256 avant stockage.
                Skalle les déchiffre uniquement au moment de l&apos;appel.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {/* Réseaux sociaux — connexion OAuth directe */}
              <div className="mb-6 space-y-3">
                <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Réseaux sociaux</p>

                {/* LinkedIn */}
                {(() => {
                  const liConnected = outboundList.some((i) => i.provider === "LINKEDIN_OAUTH");
                  return (
                    <div className="flex items-center justify-between rounded-lg border p-4">
                      <div className="flex items-center gap-3">
                        <Linkedin className="h-5 w-5 text-blue-600" />
                        <div>
                          <p className="text-sm font-medium">LinkedIn</p>
                          <p className="text-xs text-muted-foreground">Publiez directement vos posts</p>
                        </div>
                      </div>
                      {liConnected ? (
                        <span className="flex items-center gap-1 text-xs font-medium text-green-600">
                          <CheckCircle2 className="h-3.5 w-3.5" /> Connecté
                        </span>
                      ) : (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => (window.location.href = `/api/integrations/linkedin/connect?workspaceId=${workspaceId}`)}
                        >
                          Connecter
                        </Button>
                      )}
                    </div>
                  );
                })()}

                {/* Facebook & Instagram */}
                <div className="rounded-lg border">
                  <div className="flex items-center justify-between p-4">
                    <div className="flex items-center gap-3">
                      <div className="flex -space-x-1">
                        <Facebook className="h-5 w-5 text-blue-500" />
                        <Instagram className="h-5 w-5 text-pink-500" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">Facebook & Instagram</p>
                        <p className="text-xs text-muted-foreground">
                          Réception des commentaires, DMs automatiques, engagement
                        </p>
                      </div>
                    </div>
                    {metaStatus?.connected ? (
                      <span className="flex items-center gap-1 text-xs font-medium text-green-600">
                        <CheckCircle2 className="h-3.5 w-3.5" />
                        {metaStatus.accounts.length} page{metaStatus.accounts.length > 1 ? "s" : ""}
                      </span>
                    ) : metaStatus?.hasFacebookLogin ? (
                      <Button size="sm" variant="outline" onClick={handleOpenPagesModal}>
                        Sélectionner une Page
                      </Button>
                    ) : (
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() =>
                          signIn("facebook", {
                            callbackUrl: `/marketing-os/settings/integrations?meta=connect`,
                          })
                        }
                      >
                        Connecter avec Facebook
                      </Button>
                    )}
                  </div>

                  {/* Pages connectées */}
                  {metaStatus?.accounts && metaStatus.accounts.length > 0 && (
                    <div className="border-t divide-y">
                      {metaStatus.accounts.map((account) => {
                        const isExpiringSoon =
                          account.tokenExpiresAt &&
                          new Date(account.tokenExpiresAt).getTime() - Date.now() < 7 * 24 * 60 * 60 * 1000;
                        return (
                          <div key={account.id} className="flex items-center justify-between px-4 py-3">
                            <div className="space-y-0.5">
                              <div className="flex items-center gap-2">
                                <Facebook className="h-3.5 w-3.5 text-blue-500" />
                                <p className="text-sm font-medium">{account.facebookPageName}</p>
                                {isExpiringSoon && (
                                  <span className="flex items-center gap-0.5 text-xs text-amber-600">
                                    <AlertTriangle className="h-3 w-3" /> Token expire bientôt
                                  </span>
                                )}
                              </div>
                              {account.instagramUsername && (
                                <div className="flex items-center gap-2">
                                  <Instagram className="h-3.5 w-3.5 text-pink-500" />
                                  <p className="text-xs text-muted-foreground">@{account.instagramUsername}</p>
                                </div>
                              )}
                              <div className="flex items-center gap-2 pt-1">
                                <Switch
                                  id={`auto-dm-${account.id}`}
                                  checked={account.autoGenerateDMs}
                                  disabled={toggleLoading === account.id}
                                  onCheckedChange={(checked) => handleToggleAutoGenerate(account.id, checked)}
                                />
                                <Label htmlFor={`auto-dm-${account.id}`} className="text-xs text-muted-foreground cursor-pointer">
                                  Auto-génération DMs
                                  {toggleLoading === account.id && <Loader2 className="inline h-3 w-3 ml-1 animate-spin" />}
                                </Label>
                              </div>
                            </div>
                            <div className="flex items-center gap-2">
                              {metaStatus.hasFacebookLogin && (
                                <Button
                                  size="sm"
                                  variant="ghost"
                                  className="text-muted-foreground h-8 px-2"
                                  onClick={handleOpenPagesModal}
                                  title="Ajouter une autre page"
                                >
                                  <RefreshCw className="h-3.5 w-3.5" />
                                </Button>
                              )}
                              <Button
                                size="sm"
                                variant="ghost"
                                className="text-destructive hover:text-destructive h-8 px-2"
                                onClick={() => setDisconnectMetaId(account.id)}
                              >
                                <Trash2 className="h-3.5 w-3.5" />
                              </Button>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              </div>

              {loading ? (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Chargement…
                </div>
              ) : (
                <div className="grid gap-3 sm:grid-cols-2">
                  {providers.map((p) => {
                    const connected = outboundList.some(
                      (i) => i.provider === p.value
                    );
                    return (
                      <Card
                        key={p.value}
                        className="cursor-pointer transition-colors hover:bg-muted/50"
                        onClick={() => {
                          if (apiError) return;
                          setConnectProvider(p.value);
                          setConnectApiKey("");
                        }}
                      >
                        <CardHeader className="pb-2">
                          <div className="flex items-center justify-between">
                            <CardTitle className="text-base">{p.label}</CardTitle>
                            {connected ? (
                              <span className="text-xs font-medium text-green-600">
                                Connecté
                              </span>
                            ) : (
                              <ExternalLink className="h-4 w-4 text-muted-foreground" />
                            )}
                          </div>
                          <CardDescription className="text-sm">
                            {p.description}
                          </CardDescription>
                        </CardHeader>
                      </Card>
                    );
                  })}
                </div>
              )}

              {outboundList.length > 0 && (
                <div className="mt-6">
                  <h4 className="text-sm font-medium mb-2">Configurés</h4>
                  <ul className="divide-y rounded-md border">
                    {outboundList.map((i) => (
                      <li
                        key={i.id}
                        className="flex items-center justify-between px-4 py-2"
                      >
                        <span>
                          {providers.find((p) => p.value === i.provider)?.label ?? i.provider}
                        </span>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-destructive"
                          onClick={(e) => {
                            e.stopPropagation();
                            setDeleteId(i.id);
                          }}
                        >
                          Supprimer
                        </Button>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Modal: créer clé — avertissement puis affichage une fois */}
      <Dialog open={createKeyOpen} onOpenChange={(open) => !open && handleCloseCreateKeyModal()}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>
              {createdKey ? "Clé créée — copiez-la maintenant" : "Créer une clé secrète"}
            </DialogTitle>
            <DialogDescription>
              {createdKey
                ? "Cette clé ne sera plus jamais affichée. Stockez-la dans un endroit sûr (ex: gestionnaire de mots de passe)."
                : "Un nom optionnel pour identifier cette clé (ex: Zapier, Make)."}
            </DialogDescription>
          </DialogHeader>
          {!createdKey ? (
            <>
              <div className="space-y-2">
                <Label htmlFor="key-name">Nom (optionnel)</Label>
                <Input
                  id="key-name"
                  placeholder="ex: Zapier Key"
                  value={newKeyName}
                  onChange={(e) => setNewKeyName(e.target.value)}
                />
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setCreateKeyOpen(false)}>
                  Annuler
                </Button>
                <Button onClick={handleCreateKey} disabled={createKeyLoading}>
                  {createKeyLoading ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    "Générer la clé"
                  )}
                </Button>
              </DialogFooter>
            </>
          ) : (
            <>
              <div className="rounded-lg bg-muted p-4 font-mono text-sm break-all">
                {createdKey}
              </div>
              <Button variant="outline" onClick={handleCopyKey} className="gap-2">
                <Copy className="h-4 w-4" />
                Copier la clé
              </Button>
              <DialogFooter>
                <Button onClick={handleCloseCreateKeyModal}>
                  J&apos;ai copié la clé
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Modal: connecter un provider Outbound */}
      <Dialog
        open={!!connectProvider}
        onOpenChange={(open) => !open && setConnectProvider(null)}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {connectProvider &&
                providers.find((p) => p.value === connectProvider)?.label}{" "}
              — Configuration
            </DialogTitle>
            <DialogDescription>
              {connectProvider === "WORDPRESS"
                ? "Entrez l'URL de votre site et vos identifiants WordPress (mot de passe d'application)."
                : connectProvider === "STRAPI"
                ? "Connectez votre instance Strapi v4/v5 via un API Token full-access."
                : connectProvider === "SANITY"
                ? "Connectez votre projet Sanity avec un token d'écriture."
                : connectProvider === "CONTENTFUL"
                ? "Connectez votre espace Contentful avec un Content Management Token."
                : connectProvider === "REST_API"
                ? "Connectez n'importe quelle API REST. Skalle POSTera le JSON de l'article sur votre endpoint."
                : connectProvider === "WEBHOOK" || connectProvider === "CUSTOM_CRM"
                ? 'Entrez l\'URL du endpoint. Format JSON optionnel : {"url":"...","secret":"..."} ou {"url":"...","token":"Bearer xxx"}'
                : "Entrez la clé API fournie par le service. Elle sera chiffrée avant d'être stockée."}
            </DialogDescription>
          </DialogHeader>

          {connectProvider === "WORDPRESS" ? (
            <div className="space-y-3">
              <div className="space-y-1">
                <Label htmlFor="wp-site-url">URL du site WordPress</Label>
                <Input
                  id="wp-site-url"
                  placeholder="https://monsite.com"
                  value={wpSiteUrl}
                  onChange={(e) => setWpSiteUrl(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="wp-username">Nom d&apos;utilisateur WordPress</Label>
                <Input
                  id="wp-username"
                  placeholder="admin"
                  value={wpUsername}
                  onChange={(e) => setWpUsername(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="wp-app-password">Mot de passe d&apos;application</Label>
                <Input
                  id="wp-app-password"
                  type="password"
                  placeholder="xxxx xxxx xxxx xxxx xxxx xxxx"
                  value={wpAppPassword}
                  onChange={(e) => setWpAppPassword(e.target.value)}
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">
                  Générez un mot de passe d&apos;application dans WordPress : Utilisateurs → Profil → Mots de passe d&apos;application
                </p>
              </div>
            </div>
          ) : connectProvider === "STRAPI" ? (
            <div className="space-y-3">
              <div className="space-y-1">
                <Label htmlFor="strapi-url">URL de votre Strapi</Label>
                <Input
                  id="strapi-url"
                  placeholder="https://cms.monsite.com"
                  value={strapiUrl}
                  onChange={(e) => setStrapiUrl(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="strapi-token">API Token (full-access)</Label>
                <Input
                  id="strapi-token"
                  type="password"
                  placeholder="Token généré dans Strapi → Settings → API Tokens"
                  value={strapiToken}
                  onChange={(e) => setStrapiToken(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="strapi-content-type">Content-type slug <span className="text-muted-foreground">(optionnel)</span></Label>
                <Input
                  id="strapi-content-type"
                  placeholder="articles"
                  value={strapiContentType}
                  onChange={(e) => setStrapiContentType(e.target.value)}
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">Slug plural de votre collection, ex: <code>blog-posts</code></p>
              </div>
            </div>
          ) : connectProvider === "SANITY" ? (
            <div className="space-y-3">
              <div className="space-y-1">
                <Label htmlFor="sanity-project-id">Project ID</Label>
                <Input
                  id="sanity-project-id"
                  placeholder="abc123de"
                  value={sanityProjectId}
                  onChange={(e) => setSanityProjectId(e.target.value)}
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">Visible dans sanity.io/manage → votre projet</p>
              </div>
              <div className="space-y-1">
                <Label htmlFor="sanity-dataset">Dataset <span className="text-muted-foreground">(optionnel)</span></Label>
                <Input
                  id="sanity-dataset"
                  placeholder="production"
                  value={sanityDataset}
                  onChange={(e) => setSanityDataset(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="sanity-token">API Token (write)</Label>
                <Input
                  id="sanity-token"
                  type="password"
                  placeholder="Token généré dans Manage → API → Tokens"
                  value={sanityToken}
                  onChange={(e) => setSanityToken(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="sanity-doc-type">Type de document <span className="text-muted-foreground">(optionnel)</span></Label>
                <Input
                  id="sanity-doc-type"
                  placeholder="article"
                  value={sanityDocType}
                  onChange={(e) => setSanityDocType(e.target.value)}
                  autoComplete="off"
                />
              </div>
            </div>
          ) : connectProvider === "CONTENTFUL" ? (
            <div className="space-y-3">
              <div className="space-y-1">
                <Label htmlFor="cf-space-id">Space ID</Label>
                <Input
                  id="cf-space-id"
                  placeholder="abc123xyz"
                  value={contentfulSpaceId}
                  onChange={(e) => setContentfulSpaceId(e.target.value)}
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">Settings → General Settings dans Contentful</p>
              </div>
              <div className="space-y-1">
                <Label htmlFor="cf-token">Content Management Token</Label>
                <Input
                  id="cf-token"
                  type="password"
                  placeholder="Token généré dans Settings → API Keys → Content management tokens"
                  value={contentfulToken}
                  onChange={(e) => setContentfulToken(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="cf-env-id">Environment <span className="text-muted-foreground">(optionnel)</span></Label>
                <Input
                  id="cf-env-id"
                  placeholder="master"
                  value={contentfulEnvId}
                  onChange={(e) => setContentfulEnvId(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="cf-content-type-id">Content Type ID <span className="text-muted-foreground">(optionnel)</span></Label>
                <Input
                  id="cf-content-type-id"
                  placeholder="blogPost"
                  value={contentfulContentTypeId}
                  onChange={(e) => setContentfulContentTypeId(e.target.value)}
                  autoComplete="off"
                />
              </div>
            </div>
          ) : connectProvider === "REST_API" ? (
            <div className="space-y-3">
              <div className="space-y-1">
                <Label htmlFor="rest-url">URL de l&apos;endpoint</Label>
                <Input
                  id="rest-url"
                  placeholder="https://api.monsite.com/posts"
                  value={restApiUrl}
                  onChange={(e) => setRestApiUrl(e.target.value)}
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">Skalle fera un POST JSON sur cette URL</p>
              </div>
              <div className="space-y-1">
                <Label htmlFor="rest-token">Bearer Token <span className="text-muted-foreground">(optionnel)</span></Label>
                <Input
                  id="rest-token"
                  type="password"
                  placeholder="Token d'authentification"
                  value={restApiToken}
                  onChange={(e) => setRestApiToken(e.target.value)}
                  autoComplete="off"
                />
              </div>
              <div className="space-y-1">
                <Label htmlFor="rest-field-map">Mapping des champs <span className="text-muted-foreground">(optionnel, JSON)</span></Label>
                <Input
                  id="rest-field-map"
                  placeholder={`{"title":"heading","content":"body"}`}
                  value={restApiFieldMap}
                  onChange={(e) => setRestApiFieldMap(e.target.value)}
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">
                  Si votre API utilise d&apos;autres noms de champs que <code>title</code>/<code>content</code>/<code>excerpt</code>
                </p>
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <Label htmlFor="api-key">
                {connectProvider === "WEBHOOK" || connectProvider === "CUSTOM_CRM"
                  ? "URL du endpoint"
                  : "Clé API"}
              </Label>
              <Input
                id="api-key"
                type={connectProvider === "WEBHOOK" || connectProvider === "CUSTOM_CRM" ? "url" : "password"}
                placeholder={
                  connectProvider === "WEBHOOK"
                    ? "https://hooks.zapier.com/..."
                    : connectProvider === "CUSTOM_CRM"
                    ? "https://api.moncrm.com/contacts"
                    : "Coller la clé ici"
                }
                value={connectApiKey}
                onChange={(e) => setConnectApiKey(e.target.value)}
                autoComplete="off"
              />
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setConnectProvider(null)}>
              Annuler
            </Button>
            <Button
              onClick={handleConnectOutbound}
              disabled={
                connectLoading ||
                (connectProvider === "WORDPRESS"
                  ? !wpSiteUrl.trim() || !wpUsername.trim() || !wpAppPassword.trim()
                  : connectProvider === "STRAPI"
                  ? !strapiUrl.trim() || !strapiToken.trim()
                  : connectProvider === "SANITY"
                  ? !sanityProjectId.trim() || !sanityToken.trim()
                  : connectProvider === "CONTENTFUL"
                  ? !contentfulSpaceId.trim() || !contentfulToken.trim()
                  : connectProvider === "REST_API"
                  ? !restApiUrl.trim()
                  : !connectApiKey.trim())
              }
            >
              {connectLoading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                "Enregistrer (chiffré)"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Confirm revoke */}
      <Dialog open={!!revokeId} onOpenChange={(open) => !open && setRevokeId(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Révoquer cette clé ?</DialogTitle>
            <DialogDescription>
              Toute requête utilisant cette clé échouera immédiatement. Cette action est irréversible.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setRevokeId(null)}>
              Annuler
            </Button>
            <Button
              variant="destructive"
              onClick={handleRevoke}
              disabled={revokeLoading}
            >
              {revokeLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Révoquer"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Confirm delete integration */}
      <Dialog open={!!deleteId} onOpenChange={(open) => !open && setDeleteId(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Supprimer cette intégration ?</DialogTitle>
            <DialogDescription>
              La clé stockée sera supprimée. Vous pourrez la reconfigurer plus tard.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteId(null)}>
              Annuler
            </Button>
            <Button
              variant="destructive"
              onClick={handleDeleteIntegration}
              disabled={deleteLoading}
            >
              {deleteLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Supprimer"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal: sélectionner une Page Facebook */}
      <Dialog open={pagesModalOpen} onOpenChange={(open) => !open && setPagesModalOpen(false)}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Facebook className="h-5 w-5 text-blue-500" />
              Sélectionner une Page Facebook
            </DialogTitle>
            <DialogDescription>
              Choisissez la Page à connecter. Le compte Instagram Business lié sera automatiquement associé.
            </DialogDescription>
          </DialogHeader>

          {pagesLoading ? (
            <div className="flex items-center justify-center py-8 gap-2 text-muted-foreground">
              <Loader2 className="h-5 w-5 animate-spin" />
              Chargement des pages…
            </div>
          ) : facebookPages.length === 0 ? (
            <div className="py-6 text-center text-sm text-muted-foreground">
              <p>Aucune Page Facebook trouvée.</p>
              <p className="mt-1 text-xs">Assurez-vous d'administrer au moins une Page.</p>
            </div>
          ) : (
            <ul className="divide-y rounded-md border max-h-72 overflow-y-auto">
              {facebookPages.map((page) => {
                const alreadyConnected = metaStatus?.accounts.some(
                  (a) => a.facebookPageName === page.name
                );
                return (
                  <li key={page.id} className="flex items-center justify-between px-4 py-3">
                    <div>
                      <p className="text-sm font-medium">{page.name}</p>
                      {page.category && (
                        <p className="text-xs text-muted-foreground">{page.category}</p>
                      )}
                    </div>
                    {alreadyConnected ? (
                      <span className="flex items-center gap-1 text-xs text-green-600">
                        <CheckCircle2 className="h-3.5 w-3.5" /> Connectée
                      </span>
                    ) : (
                      <Button
                        size="sm"
                        disabled={connectingPageId === page.id}
                        onClick={() => handleConnectPage(page.id, page.name)}
                      >
                        {connectingPageId === page.id ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          "Connecter"
                        )}
                      </Button>
                    )}
                  </li>
                );
              })}
            </ul>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setPagesModalOpen(false)}>
              Fermer
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Confirm disconnect Meta page */}
      <Dialog open={!!disconnectMetaId} onOpenChange={(open) => !open && setDisconnectMetaId(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Déconnecter cette Page ?</DialogTitle>
            <DialogDescription>
              Les webhooks et l'auto-génération de DMs seront désactivés pour cette Page. Vous pourrez la reconnecter plus tard.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDisconnectMetaId(null)}>
              Annuler
            </Button>
            <Button
              variant="destructive"
              onClick={handleDisconnectMeta}
              disabled={disconnectMetaLoading}
            >
              {disconnectMetaLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Déconnecter"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
