/**
 * Storyboard Templates — multi-shot video formats.
 *
 * Each template defines N plans (shots) that are generated as separate clips
 * and stitched in order. This produces authentic multi-cut UGC ads vs the
 * single-shot loop generated by standard formats.
 *
 * Each plan's contentDirection becomes the `userInstructions` arg passed to
 * buildVideoPrompt(), combined with the plan's movementType, the job's ugcStyle,
 * script timing cues, and the UGC base humanization prompt.
 */

export type StoryboardPlan = {
  id: string;
  label: string;
  icon: string;
  durationSeconds: number;
  movementType: string;
  contentDirection: string;
  preferredModel?: string; // overrides job.videoModel for this plan
};

export type StoryboardTemplate = {
  id: string;
  label: string;
  tag: string;
  desc: string;
  icon: string;
  totalDurationSeconds: number;
  ugcStyle: string;
  plans: StoryboardPlan[];
};

export const STORYBOARD_TEMPLATES: StoryboardTemplate[] = [
  {
    id: "saas_ugc_hook",
    label: "SaaS UGC Hook — Bureau Tech",
    tag: "TikTok · Reels · Shorts",
    desc: "Le format publicitaire SaaS qui convertit le mieux en 2025. 3 plans cinématiques : accroche bureau, pitch face caméra, démo POV écran. 8 secondes qui capturent et convertissent.",
    icon: "💻",
    totalDurationSeconds: 8,
    ugcStyle: "ugc_app",
    plans: [
      {
        id: "hook",
        label: "Plan 1 — Accroche",
        icon: "☕",
        durationSeconds: 2,
        movementType: "assis",
        contentDirection: `CAMERA ANGLE: Very low angle — camera is placed at desk surface level, lens tilted upward 15–20 degrees (contre-plongée / counter-shot). The desk surface fills the very bottom of the frame.

SCENE SETUP: Modern minimalist home office. Clean white walls. A cork board with pinned paper notes visible behind the person. Grey fabric sofa partially visible in background. Dark charcoal door frame at the edge. Solid light wood desk surface fills the bottom of frame. A MacBook Pro (14", space grey) on the desk, screen partially visible.

ACTION SEQUENCE: Person is leaning forward over their desk in deep focus — absorbed in their screen. They hold a white ceramic coffee mug in their left hand casually. They suddenly look up directly at camera with an intense, knowing expression — the "did you see this?" face. Then they extend their right index finger to point deliberately at the MacBook Pro screen beside them.

ENERGY: High intensity hook — the very first frame already has the person mid-lean, already engaged. The energy spike happens in the first 0.5 seconds. This is the scroll-stopper moment.

LIGHTING: Bright clean natural window light from the front. White-balanced, 5500–6000K. No warm tint. The MacBook screen emits a faint cool-blue glow as a secondary light source.`,
      },
      {
        id: "pitch",
        label: "Plan 2 — Pitch",
        icon: "🎯",
        durationSeconds: 4,
        movementType: "statique",
        contentDirection: `CAMERA ANGLE: Selfie perspective — person holds phone at arm's length, camera slightly above eye level. Chest-to-forehead framing, natural slight upward tilt. The image fills the frame intimately.

SCENE SETUP: Same modern white-wall home office. Person has stepped back 1–2 meters from the desk. Cork board and desk partially visible in background, softly blurred. Bright, open feeling. Room feels real and lived-in, not staged.

ACTION SEQUENCE: Person speaks with genuine high energy directly into the camera, making strong eye contact. They smile naturally — the Duchenne smile that reaches the eyes. Mid-speech, they point their right index finger toward the viewer in a "this is for YOU" gesture, held for 1–2 seconds. Then they open both palms wide in an expansive "here's how it works / here's the value" explanatory gesture, hands at chest level, palms facing camera.

ENERGY: The pitch phase — rebuilding energy from the hook, now direct and conversational. The person radiates the credibility of a real creator sharing a genuine recommendation. Pacing is slightly faster than casual conversation. They know your time is valuable.

LIGHTING: Same clean natural daylight. White-balanced. Neutral skin tones, no color cast.`,
      },
      {
        id: "demo",
        label: "Plan 3 — Démo POV",
        icon: "🖥️",
        durationSeconds: 2,
        movementType: "statique",
        contentDirection: `CAMERA ANGLE: Bird's-eye point-of-view shot — camera positioned directly above the desk, looking straight down at the laptop screen. No person's face is visible in this shot. Only hands, forearms, and the desk surface are in frame.

SCENE SETUP: Solid light wood desk surface fills the frame. MacBook Pro 14" open in the center of frame with the screen clearly legible — displaying a clean SaaS product landing page or dashboard UI. Minimal desk items at the frame edges (a coffee cup rim, notebook corner). Crisp, organized setup.

ACTION SEQUENCE: Both of the person's hands enter the frame smoothly from the bottom edge simultaneously — palms open and facing upward, fingers slightly spread, in a graceful "presenting" or "unveiling" gesture. The hands move toward the laptop screen as if framing and offering the product to the viewer. The gesture is elegant and deliberate — not rushed. The motion says "behold this."

ENERGY: The product reveal — calm, confident presentation energy. The hands are expressive but controlled. This is the "here is the thing I've been telling you about" moment.

LIGHTING: Clean, even overhead natural light. The laptop screen content is clearly readable. Crisp top-down commercial aesthetic, no shadows on the screen.`,
      },
    ],
  },
];

export function getStoryboardTemplate(id: string): StoryboardTemplate | undefined {
  return STORYBOARD_TEMPLATES.find((t) => t.id === id);
}
