/**
 * UGC Format Bank — 70 predefined scene formats for avatar video generation.
 *
 * Each format includes:
 * - `prompt`: detailed scene/environment description for the video model
 * - `appearance`: specific clothing, props, and accessories matching the scene
 * The two are combined at selection time so the generated avatar visually belongs
 * in the scene (right outfit, right props, right energy).
 */

export type UGCFormat = {
  id: string;
  label: string;
  category:
    | "studio"
    | "home"
    | "cafe"
    | "street"
    | "nature"
    | "premium"
    | "lifestyle"
    | "trending";
  icon: string;
  setting: string;
  prompt: string;
  appearance: string;
  movement: string;
  tags: string[];
};

export const UGC_FORMATS: UGCFormat[] = [

  // ── STUDIO & SETUP ──────────────────────────────────────────────────────────

  {
    id: "ring_light_desk",
    label: "Ring light & micro",
    category: "studio",
    icon: "🎙️",
    setting: "Bureau minimaliste, ring light, micro condensateur argenté",
    prompt: "Professional home studio setup: centered in front of a large ring light casting soft, even illumination. Behind: a minimal desk with a silver large-diaphragm condenser microphone on a boom arm, a blurred MacBook, and a small succulent. Warm grey acoustic foam panels on the wall. Shallow depth of field, professional creator aesthetic.",
    appearance: "Subject wears a clean fitted black or navy crew-neck sweatshirt or hoodie — simple, camera-ready creator look. No jewelry or minimal stud earrings. Hair neatly styled. Expression: confident and approachable.",
    movement: "statique",
    tags: ["micro", "ring light", "studio", "creator", "podcast"],
  },
  {
    id: "podcast_studio",
    label: "Podcast studio",
    category: "studio",
    icon: "🎧",
    setting: "Studio podcast pro, 2 micros, casques, éclairage tamisé",
    prompt: "Intimate podcast recording studio: seated at a dark wooden table. A large Shure SM7B microphone on a boom arm in the foreground. Headphones resting on the table. Warm amber studio lighting from LED panels. Blurred background shows acoustic panels, an empty second chair, and a monitor displaying waveforms.",
    appearance: "Subject wears a smart-casual button-up shirt in dark blue or olive, sleeves rolled to the elbows. Over-ear headphones resting around the neck. Relaxed, intellectually engaged expression.",
    movement: "assis",
    tags: ["podcast", "micro", "studio", "audio"],
  },
  {
    id: "asmr_setup",
    label: "Setup ASMR",
    category: "studio",
    icon: "🎤",
    setting: "Micro ASMR face caméra, fond sombre, lumière froide",
    prompt: "ASMR content setup: subject very close to camera behind an oversized binaural microphone with foam pop shields. Near darkness, single cool-white ring light. Background is pure black with soft bokeh fairy lights. Small shelf with crystals, a candle flame, and a glass of water at frame edge.",
    appearance: "Subject wears a soft oversized cream or dusty pink knit sweater. No makeup or very natural makeup. Hair loose and soft. Expression: calm, gentle, whispering mood. Fingernails neutral or unpainted.",
    movement: "statique",
    tags: ["asmr", "micro", "dark", "intimate", "fairy lights"],
  },
  {
    id: "white_studio",
    label: "Studio fond blanc",
    category: "studio",
    icon: "⬜",
    setting: "Fond blanc épuré, éclairage pro, look publicité",
    prompt: "Professional advertising studio: seamless pure white cyclorama background, three-point studio lighting eliminating all shadows. Clean commercial look with slight vignette. Magazine-quality, fashion editorial aesthetic.",
    appearance: "Subject wears a tailored outfit in a single bold color — all-red, all-camel, or all-white ensemble. Minimal jewelry. Clean blowout hair or sleek bun. Commercial model posture and expression.",
    movement: "statique",
    tags: ["blanc", "studio", "épuré", "publicité", "commercial"],
  },
  {
    id: "neon_studio",
    label: "Studio néons colorés",
    category: "studio",
    icon: "🌈",
    setting: "Néons RGB derrière, fond sombre, ambiance tech",
    prompt: "Gaming and tech creator studio: dark wall covered in multi-colored LED neon strips in purple, blue, and pink. Glowing RGB keyboard and monitor on a desk in background. Ring light provides frontal fill. Ambient haze effect. Dynamic Gen-Z aesthetic.",
    appearance: "Subject wears an oversized graphic tee or tech-brand hoodie in dark colors. Streetwear accessories — a chain necklace, rings. Earbuds or gaming headset around neck. Edgy, confident, youth-culture expression.",
    movement: "statique",
    tags: ["néon", "rgb", "gaming", "tech", "coloré"],
  },

  // ── HOME ────────────────────────────────────────────────────────────────────

  {
    id: "bedroom_natural",
    label: "Chambre lumière naturelle",
    category: "home",
    icon: "🪟",
    setting: "Grande fenêtre, lumière naturelle douce, plantes vertes",
    prompt: "Cozy bedroom with abundant natural light: large window with sheer white curtains filtering morning light. A monstera plant in a ceramic pot at frame left. Behind: neatly made bed with cream linen, bedside table with reading lamp, botanical prints on sage green wall. Golden morning light.",
    appearance: "Subject wears a soft linen matching set (top and trousers) in ivory or sage green — authentic morning look. Hair naturally textured or in a loose bun. No heavy styling. Holding a ceramic coffee mug in both hands.",
    movement: "statique",
    tags: ["chambre", "fenêtre", "plantes", "naturel", "matin"],
  },
  {
    id: "bedroom_fairy_lights",
    label: "Chambre fairy lights",
    category: "home",
    icon: "✨",
    setting: "Lumières guirlandes, ambiance tamisée, mood cozy",
    prompt: "Dreamy bedroom at night: warm bokeh fairy lights strung across the wall, creating hundreds of soft gold circles. Subject lit by a small warm LED panel. Polaroid photos hanging behind, books on the nightstand, soft throw blankets visible.",
    appearance: "Subject wears a cozy oversized fleece or knit cardigan in camel or blush pink, over a simple cami or tee. Hair in a messy bun with a few face-framing pieces out. Relaxed, dreamy expression. A blanket partly draped over shoulders.",
    movement: "statique",
    tags: ["fairy lights", "chambre", "nuit", "cozy", "bokeh"],
  },
  {
    id: "living_room_sofa",
    label: "Salon canapé velours",
    category: "home",
    icon: "🛋️",
    setting: "Canapé velours émeraude, lampe vintage, coussins dorés",
    prompt: "Stylish living room: seated on an emerald green velvet sofa with gold throw cushions. A vintage arc floor lamp provides warm ambient light. Coffee table with art books, dried pampas grass in a vase, and gallery wall with abstract prints. Afternoon soft light.",
    appearance: "Subject wears a chic neutral outfit — wide-leg beige trousers and a fitted camel turtleneck or a silk blouse. Hair elegantly styled. Gold earrings. Relaxed seated posture, one leg crossed. Holding or next to a glass of wine or tea.",
    movement: "assis",
    tags: ["salon", "canapé", "velours", "déco", "vintage"],
  },
  {
    id: "kitchen_morning",
    label: "Cuisine matinale",
    category: "home",
    icon: "☕",
    setting: "Îlot de cuisine, café fumant, lumière soleil matinal",
    prompt: "Bright modern kitchen in morning light: standing at a white marble kitchen island. On the counter: a French press with steam rising, fresh white tulips in a glass vase, an open cookbook, and a bowl of oranges. Warm sunlight at 45 degrees.",
    appearance: "Subject wears a casual linen shirt in light blue or white, half-tucked into relaxed trousers or jeans. Hair effortlessly styled. Holding a large ceramic mug with both hands. Natural, no-makeup or minimal makeup look.",
    movement: "statique",
    tags: ["cuisine", "café", "matin", "marbre", "fleurs"],
  },
  {
    id: "home_office",
    label: "Bureau à domicile",
    category: "home",
    icon: "💻",
    setting: "Bureau blanc, Mac, plantes, étagères en fond",
    prompt: "Minimalist home office: standing in front of a wooden desk with a blurred Apple MacBook Pro, a ceramic desk organizer, a small potted cactus, and a glass of water. Behind: white bookshelves with books and earth-tone objects, and a fiddle-leaf fig in the corner. Natural light from left.",
    appearance: "Subject wears smart-casual workwear — a well-fitted button-up shirt in white or pale blue, tucked into slim dark trousers or a pencil skirt. Reading glasses pushed up on head. Confident, professional expression.",
    movement: "statique",
    tags: ["bureau", "mac", "travail", "plantes", "minimaliste"],
  },
  {
    id: "bathroom_mirror",
    label: "Salle de bain miroir",
    category: "home",
    icon: "🪞",
    setting: "Grand miroir, lumière chaude, produits beauté disposés",
    prompt: "Chic bathroom vanity area: standing before a large round mirror with warm LED lighting. Marble countertop with neatly arranged skincare products, a scented candle, fresh eucalyptus sprigs in a small vase, and a glass perfume bottle. White subway tile background.",
    appearance: "Subject wears a soft waffle-knit robe in white or blush, cinched at the waist. Hair wrapped in a matching towel turban or down and freshly washed. Holding a skincare product or serum bottle. Minimal skin-glow makeup.",
    movement: "statique",
    tags: ["salle de bain", "miroir", "beauté", "skincare", "spa"],
  },
  {
    id: "library_reading",
    label: "Bibliothèque books",
    category: "home",
    icon: "📚",
    setting: "Mur de livres du sol au plafond, lampe bureau",
    prompt: "Personal library: floor-to-ceiling bookshelf filled with hundreds of colorful spines. A vintage globe, small bronze sculpture, and reading glasses on a wooden ladder nearby. A warm incandescent desk lamp from the left. Academic, cozy atmosphere.",
    appearance: "Subject wears a classic crew-neck fisherman sweater in off-white or burgundy, with dark slim-fit trousers. Tortoiseshell glasses worn naturally. Hair neat and simple. Holding an open book or with one finger marking a page.",
    movement: "statique",
    tags: ["bibliothèque", "livres", "lecture", "vintage", "intellectuel"],
  },
  {
    id: "window_city_view",
    label: "Fenêtre vue sur la ville",
    category: "home",
    icon: "🏙️",
    setting: "Grandes baies vitrées, vue urbaine, contre-jour dramatique",
    prompt: "Floor-to-ceiling panoramic window overlooking a cityscape: silhouetted by golden late-afternoon light. Behind: tall buildings and a cloudy sky. A chair and a small side table with a coffee cup at frame edge. Cinematic, editorial quality.",
    appearance: "Subject wears a sleek fitted midi dress or a tailored blazer over trousers in charcoal or deep navy — architectural silhouette that works beautifully against the window light. Minimal jewelry. Confident, contemplative posture.",
    movement: "statique",
    tags: ["fenêtre", "ville", "vue", "lumière", "cinématique"],
  },
  {
    id: "plants_corner",
    label: "Jungle urbaine",
    category: "home",
    icon: "🌿",
    setting: "Coin jungle, 10+ plantes tropicales, lumière douce",
    prompt: "Urban jungle interior: surrounded by lush tropical plants — monstera, pothos, bird of paradise, hanging macramé planters. Dappled light from a nearby window. Rattan shelf with terracotta pots, watering cans, and a small speaker. Green, boho-chic.",
    appearance: "Subject wears earthy, bohemian-inspired clothing — a rust-orange linen wide-leg jumpsuit or sage green wrap dress. Wooden or clay bead jewelry. Hair loose with natural waves. Watering can in hand or touching a plant leaf gently.",
    movement: "statique",
    tags: ["plantes", "jungle", "botanique", "boho", "tropical"],
  },
  {
    id: "rainy_window",
    label: "Pluie sur la vitre",
    category: "home",
    icon: "🌧️",
    setting: "Grande fenêtre sous la pluie, reflets, jour gris",
    prompt: "Rainy day by a large window: rain droplets streaming down floor-to-ceiling glass. Outside: wet pavement reflecting neon shop lights, blurred pedestrians with umbrellas. Inside: warm contrast lighting. Melancholic, introspective autumn mood.",
    appearance: "Subject wears a chunky oversized knit sweater in oatmeal or charcoal grey, with comfortable wide-leg lounge pants. Hair loosely tied back. Holding a steaming mug with both hands. A plaid throw blanket draped over shoulders.",
    movement: "statique",
    tags: ["pluie", "fenêtre", "automne", "cozy", "réflexion"],
  },

  // ── CAFÉ & URBAN INDOOR ─────────────────────────────────────────────────────

  {
    id: "coffee_shop_busy",
    label: "Coffee shop animé",
    category: "cafe",
    icon: "☕",
    setting: "Baristas actifs derrière, machines à café, clients flous",
    prompt: "Busy specialty coffee shop: behind, baristas in aprons work at gleaming espresso machines. Blurred customers at wooden tables. Pendant industrial lights from exposed brick ceiling. Chalk menu board, glass pastry case with croissants. Urban, authentic UGC.",
    appearance: "Subject wears a casual smart look — a fitted cream or terracotta turtleneck and dark jeans or trousers. A small tote bag on one shoulder. Holding a takeaway coffee cup or a ceramic flat white. Hair effortlessly styled.",
    movement: "statique",
    tags: ["café", "barista", "animé", "brique", "quotidien"],
  },
  {
    id: "parisian_cafe_terrace",
    label: "Café parisien",
    category: "cafe",
    icon: "🥐",
    setting: "Terrasse zinc, bistrot classique, rues parisiennes fond",
    prompt: "Classic Parisian café terrace: seated at a small round zinc-topped bistro table. Ceramic espresso cup and a croissant on a white plate on the table. Wicker chairs, red awning overhead. Haussmann building façade, iron balconies, and cobblestone street behind.",
    appearance: "Subject wears quintessential Parisian chic — a beige or navy trench coat over a simple striped breton marinière top and dark fitted trousers. A small leather crossbody bag on the table. French silk scarf around the neck. Sun-kissed minimal makeup.",
    movement: "assis",
    tags: ["paris", "café", "terrasse", "croissant", "haussmann"],
  },
  {
    id: "aesthetic_cafe",
    label: "Café esthétique",
    category: "cafe",
    icon: "🌸",
    setting: "Café rose pastel, fleurs séchées, ambiance coréenne",
    prompt: "Korean-aesthetic café interior: seated at a small marble table with a matcha latte topped with latte art. Dried flower arrangements in dusty rose and cream hanging from the ceiling. Warm peach-toned walls with minimalist prints. Soft natural light.",
    appearance: "Subject wears soft pastel aesthetic clothing — a pale pink or lilac oversized cardigan over a white fitted top, with pleated mini skirt. Pearl stud earrings. Hair tied in a neat low bun with a satin ribbon or bow clip. Delicate, soft, K-fashion inspired look.",
    movement: "assis",
    tags: ["café", "coréen", "pastel", "fleurs", "aesthetic"],
  },
  {
    id: "coworking_plants",
    label: "Coworking végétal",
    category: "cafe",
    icon: "🌱",
    setting: "Espace de travail avec plantes suspendues, lumière chaude",
    prompt: "Trendy coworking space with biophilic design: seated at a long communal wooden table. Hanging plants cascade from ceiling planters. Warm Edison bulbs, exposed concrete walls, other blurred professionals with laptops. A reusable coffee cup and open notebook on the table.",
    appearance: "Subject wears professional-casual — a well-tailored blazer in earth tones (camel, terracotta, or olive) over a simple fitted tee, with slim dark jeans. A small leather laptop bag on the chair back. Confident work mode expression.",
    movement: "assis",
    tags: ["coworking", "plantes", "bureau", "pro", "bois"],
  },
  {
    id: "hotel_lobby_luxury",
    label: "Lobby hôtel luxe",
    category: "cafe",
    icon: "🏨",
    setting: "Lobby marbre, fleurs fraîches géantes, lumière tamisée",
    prompt: "5-star hotel lobby: near reception. A monumental floral installation of white and blush roses in a crystal vase on a marble pedestal behind. Grand chandelier with golden light. Uniformed staff blurred in background. Dark marble floors with gold inlays.",
    appearance: "Subject wears upscale travel attire — a structured midi dress in cream or champagne, or a tailored camel coat over a silk blouse. A luxury leather handbag (structured tote or clutch). Elegant jewelry — gold hoops or a delicate necklace. Polished, effortlessly refined look.",
    movement: "statique",
    tags: ["hôtel", "luxe", "marbre", "fleurs", "grand"],
  },
  {
    id: "rooftop_bar_night",
    label: "Rooftop bar nuit",
    category: "cafe",
    icon: "🌃",
    setting: "Bar rooftop, vue skyline nocturne, cocktails, lumières",
    prompt: "Rooftop bar at night: standing at a bar counter with city lights stretching behind. Glowing cocktail glasses at frame edge. String lights overhead creating warm bokeh. Skyscrapers against a deep blue night sky. Slight breeze implied.",
    appearance: "Subject wears elegant evening-casual clothing — a sleek fitted blazer over a silk cami or a backless satin midi dress in midnight blue or emerald. Gold jewelry. Hair styled in polished waves or a sleek updo. Holding a cocktail glass.",
    movement: "statique",
    tags: ["rooftop", "nuit", "cocktail", "ville", "bar"],
  },
  {
    id: "bakery_counter",
    label: "Boulangerie artisanale",
    category: "cafe",
    icon: "🥖",
    setting: "Vitrine pâtisseries, comptoir bois, pain frais visible",
    prompt: "Artisan bakery: in front of a glass display case filled with golden croissants, pain au chocolat, fruit tarts, and sliced sourdough. Open kitchen behind with baker working. Flour-dusted surfaces, baskets of baguettes. Authentic French boulangerie.",
    appearance: "Subject wears a casual weekend look — a striped linen shirt in blue and white, light rolled-up chinos, and white sneakers. A canvas market bag on one arm, possibly holding a wrapped baguette. Relaxed, cheerful morning expression.",
    movement: "statique",
    tags: ["boulangerie", "pâtisserie", "pain", "artisan", "vitrine"],
  },
  {
    id: "bookshop_indie",
    label: "Librairie indépendante",
    category: "cafe",
    icon: "📖",
    setting: "Rayons colorés, petite librairie, lumière douce",
    prompt: "Independent bookshop interior: a narrow aisle flanked by tall wooden shelves packed with colorful paperbacks and hardcovers. Staff picks cards on shelves. Vintage incandescent lighting. A display table with stacked books and a hand-lettered sign.",
    appearance: "Subject wears a relaxed intellectual look — corduroy blazer in rust or forest green over a simple white tee, with light wash straight jeans. Round tortoiseshell glasses. Holding an open book, bookmark visible. Canvas tote bag with book spines peeking out.",
    movement: "statique",
    tags: ["librairie", "livres", "indépendant", "cozy", "vintage"],
  },
  {
    id: "florist_shop",
    label: "Fleuriste en boutique",
    category: "cafe",
    icon: "💐",
    setting: "Fleuriste, seaux de fleurs fraîches, couleurs éclatantes",
    prompt: "Flower shop interior: surrounded by buckets overflowing with fresh-cut peonies, ranunculus, eucalyptus, and garden roses. Refrigerated cases, scattered petals and ribbon rolls on the wooden counter. Fragrant, colorful, romantic artisan environment.",
    appearance: "Subject wears a florist's apron in natural linen over a relaxed floral-print blouse or a simple white shirt. Hair loosely pinned back. Holding a fresh bouquet being arranged, or tying ribbon around stems. Floral print or earthy tones throughout.",
    movement: "statique",
    tags: ["fleuriste", "fleurs", "couleur", "artisan", "boutique"],
  },
  {
    id: "craft_beer_bar",
    label: "Bar à bières artisanales",
    category: "cafe",
    icon: "🍺",
    setting: "Bar bières pression, bois sombre, éclairage tamisé",
    prompt: "Craft beer bar: standing at a long dark wooden bar. Behind: twenty-plus tap handles, a chalk menu board, and shelves with branded glasses. Warm Edison bulbs. Bartender blurred in background. Other patrons at high stools.",
    appearance: "Subject wears casual urban clothing — a slim-fit henley shirt in dark navy or forest green, dark slim jeans, and Chelsea boots. A watch on the wrist. Relaxed, social expression. Holding or about to lift a tulip glass of amber craft beer.",
    movement: "statique",
    tags: ["bar", "bière", "artisanal", "soirée", "convivial"],
  },

  // ── OUTDOOR STREET & URBAN ──────────────────────────────────────────────────

  {
    id: "busy_street",
    label: "Rue commerçante",
    category: "street",
    icon: "🛍️",
    setting: "Rue animée, passants flous, façades commerciales",
    prompt: "Busy commercial high street: walking toward camera on a wide pavement lined with shop fronts and colorful awnings. Blurred pedestrians create natural motion blur behind. A red double-decker bus partially visible. Overcast bright daylight, no harsh shadows.",
    appearance: "Subject wears stylish everyday streetwear — a fitted leather or denim jacket over a graphic tee, straight-leg jeans, and white sneakers. Small designer crossbody bag. Sunglasses on, hair naturally wind-styled. Confident urban stride.",
    movement: "marche_approche",
    tags: ["rue", "passants", "shopping", "urbain", "animation"],
  },
  {
    id: "market_outdoor",
    label: "Marché en plein air",
    category: "street",
    icon: "🍊",
    setting: "Étals colorés de fruits, marché de plein air, foule",
    prompt: "Vibrant outdoor market: walking through a farmers market between stalls overflowing with bright produce — oranges, tomatoes, bundles of lavender, and flowers in buckets. Market vendors and shoppers with canvas bags behind. Canvas awnings filter morning sunlight.",
    appearance: "Subject wears casual weekend chic — a linen button-front dress in warm terra cotta or sky blue, espadrille sandals. A large woven market basket over the arm, holding a small bunch of fresh flowers. Hair in a relaxed low braid or loose.",
    movement: "marche_laterale",
    tags: ["marché", "fruits", "fleurs", "plein air", "coloré"],
  },
  {
    id: "haussmann_street",
    label: "Boulevard haussmannien",
    category: "street",
    icon: "🏛️",
    setting: "Boulevard parisien, façades pierre, balcons fer forgé",
    prompt: "Classic Parisian Haussmann boulevard: walking on the pavement. Wide boulevard lined with cream limestone buildings, wrought-iron balconies, and mature plane trees with dappled shadows. A parked Vespa and flower boxes above. Other pedestrians blurred behind. Morning golden light.",
    appearance: "Subject wears a polished Parisian look — a fitted blazer in camel or ivory over dark slim trousers, pointed leather loafers or kitten heels. A structured leather handbag. Tortoiseshell sunglasses. Trench coat draped or worn. Effortlessly chic.",
    movement: "marche_approche",
    tags: ["paris", "boulevard", "haussmann", "pierre", "romantique"],
  },
  {
    id: "street_art_wall",
    label: "Mur street art",
    category: "street",
    icon: "🎨",
    setting: "Grand mural coloré, quartier tendance, trottoir",
    prompt: "Urban street art district: standing in front of a large-scale colorful mural covering a 3-story building — vivid geometrics and a painted portrait in blues, yellows, and reds. Cracked pavement, industrial chain-link at the edges. Other pedestrians blurred passing.",
    appearance: "Subject wears bold streetwear — oversized vintage graphic tee, high-waisted cargo pants in olive or black, chunky sneakers. Layered necklaces, rings. A backward snapback or bucket hat. Bold, creative, street-culture expression. An accessory in a contrasting pop color.",
    movement: "statique",
    tags: ["street art", "mural", "urbain", "art", "couleur"],
  },
  {
    id: "metro_corridor",
    label: "Couloir de métro",
    category: "street",
    icon: "🚇",
    setting: "Couloirs colorés, carrelage rétro, tiles métro",
    prompt: "Graphic metro station corridor: walking through a tunnel lined with distinctive colored ceramic tiles — Paris métro orange, blue, and cream geometric patterns. Fluorescent tube lighting creates hard shadows. Commuters in motion blur behind.",
    appearance: "Subject wears urban commuter style — a clean tailored coat in charcoal or camel over dark jeans, clean white sneakers or loafers. A structured backpack or laptop bag. Earbuds in. Hair neatly styled. Purposeful, on-the-move energy.",
    movement: "marche_approche",
    tags: ["métro", "souterrain", "carrelage", "parisien", "urbain"],
  },
  {
    id: "bridge_river",
    label: "Pont sur la rivière",
    category: "street",
    icon: "🌉",
    setting: "Pont historique, reflets eau, lumière dorée",
    prompt: "Historic bridge over a river at golden hour: standing at the stone railing. Below: river reflecting orange and gold from the setting sun. Ancient lampposts with warm globe lights. Willows dip toward the water. Soft out-of-focus cityscape across the river.",
    appearance: "Subject wears a romantic golden-hour outfit — a flowing midi dress in rust, burnt orange, or dusty rose, or a relaxed linen suit. Light fabric that catches the warm breeze. Delicate gold jewelry. Hair loose and slightly wind-moved. Holding the railing lightly.",
    movement: "statique",
    tags: ["pont", "rivière", "coucher de soleil", "romantique", "doré"],
  },
  {
    id: "shopping_mall",
    label: "Centre commercial",
    category: "street",
    icon: "🏬",
    setting: "Galerie lumineuse, verrière, escalators en fond",
    prompt: "Modern shopping mall interior: walking through a bright atrium. Massive glass skylight floods the space with natural light. Luxury brand storefronts on multiple levels, an escalator carrying shoppers. Polished stone floors. A large pendant chandelier overhead.",
    appearance: "Subject wears a chic shopping-day look — a fitted trench coat over a light knit or silk blouse, tailored trousers, and heeled ankle boots or clean white sneakers. Multiple designer shopping bags from luxury brands held in one hand. Polished, purposeful.",
    movement: "marche_approche",
    tags: ["mall", "galerie", "shopping", "escalator", "luxe"],
  },
  {
    id: "parking_underground",
    label: "Parking souterrain",
    category: "street",
    icon: "🅿️",
    setting: "Néons de parking, béton brut, lignes graphiques",
    prompt: "Underground parking garage: standing in front of a sleek car, concrete pillars, yellow line markings on the ground, and fluorescent tube lighting creating hard contrasts. Low ceiling, industrial aesthetic. A sports car partially visible in background.",
    appearance: "Subject wears high-fashion editorial clothing — a structured all-black or monochrome outfit, sharp tailored blazer or leather jacket, slim trousers, and leather boots. Minimal accessories. Strong, cinematic, editorial model posture.",
    movement: "statique",
    tags: ["parking", "béton", "néon", "industriel", "voiture"],
  },
  {
    id: "airport_terminal",
    label: "Terminal d'aéroport",
    category: "street",
    icon: "✈️",
    setting: "Terminal animé, voyageurs, écrans de départs",
    prompt: "International airport terminal: walking through a bright modern terminal with floor-to-ceiling windows and the tarmac beyond. Gate signage and departure boards overhead. Other travelers with wheeled suitcases blurred in motion. Duty-free shop and coffee kiosk behind.",
    appearance: "Subject wears comfortable travel-chic clothing — a well-fitted jogger set or matching athleisure in neutral grey or black, white sneakers, an elevated puffer vest. A quality carry-on trolley or designer cabin bag. Sunglasses on forehead. Effortless travel energy.",
    movement: "marche_approche",
    tags: ["aéroport", "voyage", "terminal", "avion", "international"],
  },
  {
    id: "university_campus",
    label: "Campus universitaire",
    category: "street",
    icon: "🎓",
    setting: "Couloirs campus, étudiants en fond, architecture",
    prompt: "University campus exterior: walking down a wide path between historic stone faculty buildings with ivy-covered walls. Students in groups on benches with open laptops behind. A large campus map and notice board covered in flyers. Autumn leaves on the ground.",
    appearance: "Subject wears classic campus style — a varsity jacket or heritage quilted jacket over a simple tee, straight-leg jeans, and white New Balance sneakers. A large canvas book bag over one shoulder. A coffee cup in hand. Youthful, academic, casual.",
    movement: "marche_approche",
    tags: ["université", "campus", "étudiant", "printemps", "architectural"],
  },
  {
    id: "skatepark",
    label: "Skatepark urbain",
    category: "street",
    icon: "🛹",
    setting: "Bowl de skate, béton brut, graffitis, culture urbaine",
    prompt: "Urban skatepark: standing at the rim of a concrete bowl covered in colorful graffiti tags. Skateboarders in motion behind, blurred. Chain-link fence, industrial warehouse buildings, and spray-painted murals. Afternoon light creating hard shadows across the concrete geometry.",
    appearance: "Subject wears authentic skate culture clothing — an oversized vintage skate-brand tee tucked into baggy cargo pants, worn Vans or Nike SB sneakers. A skateboard held under one arm or leaning against leg. Backwards cap, silver rings and chains.",
    movement: "statique",
    tags: ["skate", "urbain", "béton", "graffiti", "jeunesse"],
  },

  // ── NATURE & OUTDOOR CALME ──────────────────────────────────────────────────

  {
    id: "park_trees",
    label: "Allée d'arbres",
    category: "nature",
    icon: "🌳",
    setting: "Allée de platanes, lumière filtrée, parc public",
    prompt: "Tree-lined park avenue: walking along a symmetrical path flanked by towering plane trees. Dappled sunlight creates moving shadows on the gravel below. Other park visitors tiny in the extreme background. A vintage iron bench at frame edge. Warm afternoon light.",
    appearance: "Subject wears a relaxed natural look — a cream linen blazer over a simple fitted tee, slim chinos in olive or sand, and leather loafers or minimal sneakers. A folded newspaper or book under the arm. Light relaxed weekend expression.",
    movement: "marche_approche",
    tags: ["parc", "arbres", "allée", "nature", "lumière"],
  },
  {
    id: "beach_waves",
    label: "Plage vagues douces",
    category: "nature",
    icon: "🏖️",
    setting: "Bord de mer, vagues, sable doré, ciel méditerranéen",
    prompt: "Mediterranean beach: standing on golden sand near the water's edge, soft waves lapping behind. Turquoise sea extending to a cloudless blue sky horizon. Wind gently moves hair. Seashells and smooth stones in the wet sand. Parasols and a sailboat faint in the background.",
    appearance: "Subject wears effortless beach style — a linen co-ord (shorts and open shirt) in white or sky blue for men, a floaty linen sundress or beachy co-ord for women. Barefoot in the sand or leather sandals. Sunglasses on. A straw hat in hand or worn.",
    movement: "statique",
    tags: ["plage", "mer", "vagues", "été", "méditerranée"],
  },
  {
    id: "forest_light",
    label: "Forêt lumière filtrée",
    category: "nature",
    icon: "🌲",
    setting: "Sous-bois, rayons de soleil entre les arbres, fougères",
    prompt: "Ancient forest with cathedral light: standing on a moss-covered path. Shafts of golden sunlight break through the canopy creating godray effects. Tall ferns at ground level, lichen-covered fallen logs. Misty background depth. Magical, ethereal.",
    appearance: "Subject wears earthy outdoor clothing — a fitted forest green or rust-brown waxed jacket or utility jacket over a neutral thermal, dark hiking trousers, and rugged hiking boots. A minimal backpack on shoulders. Hair natural and free.",
    movement: "statique",
    tags: ["forêt", "sous-bois", "lumière", "nature", "magique"],
  },
  {
    id: "lavender_field",
    label: "Champ de lavande",
    category: "nature",
    icon: "💜",
    setting: "Rangées de lavande violette, Provence, ciel bleu",
    prompt: "Provence lavender field in full bloom: standing in the middle of purple-violet lavender rows stretching to the horizon. A stone farmhouse visible in the far background. Bees implied, light wind bending the lavender heads. Bright Provençal sunlight.",
    appearance: "Subject wears sun-soaked Provençal style — a white or cream linen maxi dress, wide-brim straw hat (held or worn), and leather flat sandals. A small woven basket. Minimal jewelry. Tanned, natural, sun-kissed skin.",
    movement: "statique",
    tags: ["lavande", "provence", "violet", "champs", "été"],
  },
  {
    id: "mountain_panorama",
    label: "Panorama montagne",
    category: "nature",
    icon: "🏔️",
    setting: "Sommet, vue alpestre, ciel dégagé, neige",
    prompt: "Alpine mountain summit: standing at a rocky viewpoint with a dramatic mountain panorama. Snow-capped peaks in the distance, a deep blue glacier lake in the valley below. Crisp clear air. A wooden signpost and cairn of stones at the summit.",
    appearance: "Subject wears proper alpine/adventure gear — a quality puffer jacket in bright red or cobalt blue, technical hiking trousers, and trail runners or hiking boots. A light merino layer visible at the collar. A small summit pack on the back. Windswept, exhilarated expression.",
    movement: "statique",
    tags: ["montagne", "alpes", "panorama", "aventure", "neige"],
  },
  {
    id: "lakeside",
    label: "Bord de lac",
    category: "nature",
    icon: "🌊",
    setting: "Lac miroir, reflets parfaits, quiétude absolue",
    prompt: "Serene mountain lake: standing on a wooden dock extending into a perfectly calm lake. Opposite shore of pine-covered mountains reflecting symmetrically. A single rowing boat tied to a post. Morning mist just above the water surface. Absolute stillness.",
    appearance: "Subject wears a peaceful, outdoorsy look — a cozy oversized flannel shirt in red and black plaid, dark slim jeans, and waterproof boots. Hair loose. Hands in pockets, deeply relaxed posture. A warm travel mug in one hand.",
    movement: "statique",
    tags: ["lac", "reflet", "calme", "montagne", "nature"],
  },
  {
    id: "orchard_blossom",
    label: "Verger en fleurs",
    category: "nature",
    icon: "🌸",
    setting: "Cerisiers en fleurs, pétales qui tombent, printemps",
    prompt: "Japanese-style cherry blossom garden: standing beneath flowering cherry trees, soft pink petals falling around in a gentle breeze. A canopy of blossoms overhead filters soft spring light. A stone lantern and winding garden path behind. Other blossom trees in the misty distance.",
    appearance: "Subject wears romantic spring clothing — a flowing white or blush pink midi dress with delicate floral details, or a soft pastel suit for a more modern look. White or pearl jewelry. Hair adorned with a small cherry blossom sprig. Soft expression of wonder.",
    movement: "statique",
    tags: ["cerisier", "fleurs", "pétales", "printemps", "sakura"],
  },
  {
    id: "vineyard",
    label: "Terrasse de vigne",
    category: "nature",
    icon: "🍇",
    setting: "Vignes en rangées, bastide en fond, coucher de soleil",
    prompt: "French vineyard terrace at golden hour: standing among neat rows of grapevines heavy with dark grapes. A Provençal stone bastide farmhouse behind. Setting sun casts long golden light across the vines. A rustic wooden barrel and wine bottle at frame edge.",
    appearance: "Subject wears elegant rural chic — a flowing linen maxi skirt in wine red or deep ochre, a simple white linen blouse slightly billowing in the breeze, leather espadrille wedges. A glass of red wine held lightly. Warm, relaxed smile.",
    movement: "statique",
    tags: ["vigne", "vin", "provence", "coucher de soleil", "rural"],
  },
  {
    id: "sunflower_field",
    label: "Champ de tournesols",
    category: "nature",
    icon: "🌻",
    setting: "Champ de tournesols géant, lumière dorée, été",
    prompt: "Sunflower field at peak bloom: standing waist-deep in a dense field of giant sunflowers all facing the same direction. Golden late-afternoon light back-illuminates the petals creating a warm halo. Bees hover around flowers. A farm barn barely visible on the horizon.",
    appearance: "Subject wears cheerful summer clothing — a yellow or sunflower-patterned sundress or a white linen outfit that pops against the yellow backdrop. Wide-brim straw hat. Light espadrilles or bare feet in the soil. Holding a large sunflower in one hand.",
    movement: "statique",
    tags: ["tournesols", "champ", "été", "jaune", "nature"],
  },

  // ── PREMIUM & ASPIRATIONNEL ─────────────────────────────────────────────────

  {
    id: "hotel_five_star",
    label: "Suite hôtel 5 étoiles",
    category: "premium",
    icon: "🌟",
    setting: "Suite luxe, linge blanc immaculé, fleurs fraîches",
    prompt: "Five-star hotel suite: standing near a king-size bed with pristine white Egyptian cotton linens, a hotel-monogrammed throw, and a pillow arrangement. Fresh white orchids in a tall crystal vase. A door to a balcony reveals a blurred sea view. Warm lamplight.",
    appearance: "Subject wears a silk monogrammed hotel bathrobe in pure white, cinched with a velvet belt, or an elegant silk loungewear set in champagne. Luxury slippers. Hair in a classic low bun. Holding a crystal champagne flute. Radiates ease and wealth.",
    movement: "statique",
    tags: ["hôtel", "luxe", "suite", "blanc", "orchidée"],
  },
  {
    id: "yacht_deck",
    label: "Pont de yacht",
    category: "premium",
    icon: "⛵",
    setting: "Pont de yacht, mer bleue, ciel azur, voiles",
    prompt: "Luxury yacht deck on the Mediterranean: standing at the stern of a white sailing yacht. Deep blue-green sea to the horizon, another sailboat in the distance. Chrome hardware and teak deck boards glistening in sunlight. A champagne glass and sunscreen on the deck chair at frame edge.",
    appearance: "Subject wears effortless nautical luxury — a crisp white linen shirt, navy tailored shorts or white wide-leg trousers, and premium leather boat shoes. Aviator sunglasses. Hair naturally wind-tousled. A luxury watch on the wrist. Tanned, confident.",
    movement: "statique",
    tags: ["yacht", "mer", "luxe", "vacances", "méditerranée"],
  },
  {
    id: "infinity_pool",
    label: "Piscine à débordement",
    category: "premium",
    icon: "🏊",
    setting: "Piscine infinie, vue mer, mobilier blanc",
    prompt: "Infinity pool villa terrace: standing at the pool edge where the water merges with the distant blue sea. White sun loungers with fluffy towels, a cocktail on a poolside table. Bougainvillea in vivid magenta at frame left. Midday bright sunshine, crystal clear water.",
    appearance: "Subject wears a luxurious poolside look — a designer swimsuit or swim trunks in a bold color (cobalt, emerald, coral), with an open linen shirt or sarong draped over. Large designer sunglasses, an elegant straw hat. A cocktail in hand. Radiates aspirational luxury.",
    movement: "statique",
    tags: ["piscine", "luxe", "vue", "mer", "villa"],
  },
  {
    id: "penthouse_night",
    label: "Penthouse terrasse nuit",
    category: "premium",
    icon: "🌆",
    setting: "Terrasse penthouse, skyline nocturne, champagne",
    prompt: "Penthouse terrace at night overlooking a glittering city skyline: standing at a glass railing with skyscrapers lit up behind. A champagne bucket with bottles on a white marble table at frame edge. Outdoor furniture with plush cushions. Warm terrace lighting contrasts with cool blue city glow.",
    appearance: "Subject wears a polished evening outfit — a well-cut blazer in midnight navy or charcoal, with a silk shirt, fitted trousers, and oxford shoes. Or an elegant cocktail dress in black or deep jewel tone. Fine watch. A champagne flute raised. Power and success energy.",
    movement: "statique",
    tags: ["penthouse", "nuit", "champagne", "skyline", "luxe"],
  },
  {
    id: "spa_zen",
    label: "Spa & bien-être",
    category: "premium",
    icon: "🕯️",
    setting: "Spa, bougies, pierres, ambiance japonaise",
    prompt: "High-end spa relaxation area: Japanese-inspired space with dark stone walls. Floating candles in a shallow water feature. A stack of smooth grey river stones, rolled white towels, and a single orchid stem in a bamboo vase. Dimmed amber lighting from paper lanterns.",
    appearance: "Subject wears a premium spa robe in white waffle-weave texture, with spa sandals. Hair wrapped in a soft towel or pinned back. No jewelry — completely bare and clean. Holding a warm jade roller or a cup of herbal tea. Pure serenity expression.",
    movement: "statique",
    tags: ["spa", "bougies", "bien-être", "zen", "japonais"],
  },
  {
    id: "private_jet",
    label: "Jet privé",
    category: "premium",
    icon: "🛩️",
    setting: "Cabine jet privé, cuir crème, hublots, champagne",
    prompt: "Private jet interior: seated in a cream leather captain's chair. Oval windows showing blue sky and clouds beyond. A small marble-effect table holds a crystal champagne flute. Walnut wood paneling and polished metal fixtures. The far end shows another seat and a curtained galley.",
    appearance: "Subject wears high-end travel attire — a tailored cashmere sweater in camel or black over pressed slim trousers, or a luxury athleisure set. A designer carry-on visible at feet. Fine jewellery. Effortless, ultra-premium expression of casual wealth.",
    movement: "assis",
    tags: ["jet privé", "avion", "luxe", "cuir", "champagne"],
  },
  {
    id: "art_gallery",
    label: "Galerie d'art",
    category: "premium",
    icon: "🖼️",
    setting: "Galerie blanche, grandes toiles, éclairage spot",
    prompt: "Contemporary art gallery: white cube gallery space. Large-scale abstract canvases with bold geometric shapes in black, red, and gold hung on pristine white walls. Track lighting highlights art with warm focused spots. A wooden plinth with a sculptural object. Polished concrete floor.",
    appearance: "Subject wears sophisticated minimalist clothing — all-black with a single sculptural piece: a voluminous coat, a striking jacket, or a minimalist dress with an architectural silhouette. A single statement ring or earring. Impeccable posture. Cultured, self-assured art world presence.",
    movement: "statique",
    tags: ["galerie", "art", "blanc", "contemporain", "culturel"],
  },
  {
    id: "gym_premium",
    label: "Salle de sport premium",
    category: "premium",
    icon: "💪",
    setting: "Gym haut de gamme, miroirs, équipements modernes",
    prompt: "Premium fitness club: high-end gym with mirrored walls. Behind: rows of chrome dumbbells on racks, cable machines, and a functional training rig. Track lighting, luxury flooring. Other athletes blurred in background.",
    appearance: "Subject wears high-performance activewear from a premium brand — fitted technical tights or shorts in charcoal or black, a matching crop top or compression top, clean training shoes. A gym towel draped over one shoulder. Fit, confident, performance-driven look.",
    movement: "statique",
    tags: ["gym", "sport", "fitness", "miroir", "premium"],
  },

  // ── LIFESTYLE & ACTIVITÉ ────────────────────────────────────────────────────

  {
    id: "morning_jog",
    label: "Jogging matinal",
    category: "lifestyle",
    icon: "🏃",
    setting: "Parc brumeux, aurore, tenue de sport, souffle visible",
    prompt: "Early morning jog in a city park: jogging toward camera on a tree-lined path at dawn. Morning mist hangs low over the grass. Other joggers tiny in background. Fallen leaves on the path. Breath visible in cold air. City buildings barely visible through the fog.",
    appearance: "Subject wears running gear — breathable running tights, a fitted long-sleeve tech top in grey or navy, and bright running shoes with reflective strips. Earbuds in, a running armband on the forearm. Light frost-breath visible. Hair in a sporty ponytail or beanie worn.",
    movement: "marche_approche",
    tags: ["jogging", "matin", "parc", "sport", "brume"],
  },
  {
    id: "yoga_outdoor",
    label: "Yoga en extérieur",
    category: "lifestyle",
    icon: "🧘",
    setting: "Tapis yoga, coucher de soleil, mer ou montagne fond",
    prompt: "Outdoor yoga at golden hour: standing on a purple yoga mat on a clifftop or rooftop with a panoramic sunset view. The sky ablaze with orange, gold, and rose tones. A small candle, a water bottle, and a rolled towel beside the mat. Wind gently moves hair.",
    appearance: "Subject wears premium yoga wear — fitted high-waist leggings in sage green or dusty rose with a matching sports bra or fitted crop top. Bare feet on the mat. Minimal jewelry — just a delicate necklace. Hair in a sleek high bun or loose. Serene, centered expression.",
    movement: "statique",
    tags: ["yoga", "plein air", "coucher de soleil", "wellness", "spirituel"],
  },
  {
    id: "shopping_bags",
    label: "Shopping & sacs",
    category: "lifestyle",
    icon: "🛍️",
    setting: "Sacs shopping, galerie commerçante, style",
    prompt: "Fashion shopping day: walking through a high-end shopping gallery carrying multiple luxury paper shopping bags. Boutique storefronts with illuminated signage on both sides. Other shoppers and a mall fountain blurred behind. Afternoon skylight above.",
    appearance: "Subject wears a put-together shopping-day outfit — a midi wrap dress in a bold print or solid jewel tone, a statement handbag worn crossbody, and heeled mules or kitten heel sandals. Oversized sunglasses pushed up. Multiple shopping bags from recognizable luxury brands.",
    movement: "marche_approche",
    tags: ["shopping", "mode", "sacs", "galerie", "luxe"],
  },
  {
    id: "car_driver_seat",
    label: "Siège conducteur",
    category: "lifestyle",
    icon: "🚗",
    setting: "Intérieur voiture premium, tableau de bord, vue autoroute",
    prompt: "Inside a premium car from the driver's seat perspective: subject faces camera, luxury dashboard with digital displays behind, steering wheel at bottom of frame. Through windows: a blurred highway or city road in motion. Soft interior ambient lighting. A coffee cup in the cupholder.",
    appearance: "Subject wears smart-casual clothing appropriate for a driver — a fitted rollneck in camel or black, quality dark trousers. A luxury watch on the wrist. Sunglasses either worn or on the dashboard. Relaxed hands resting on the steering wheel.",
    movement: "statique",
    tags: ["voiture", "conducteur", "luxe", "route", "mobilité"],
  },
  {
    id: "train_window",
    label: "Train paysage",
    category: "lifestyle",
    icon: "🚄",
    setting: "Fenêtre TGV, paysage qui défile, lumière douce",
    prompt: "High-speed train journey: seated at a window seat of a TGV or Eurostar, blurred countryside streaming past — green fields, a village church steeple, distant hills. Table with a café crème, an open book, and AirPods case. Soft overcast light through the window.",
    appearance: "Subject wears comfortable elevated travel clothing — a quality camel or navy knit, slim dark jeans, and white clean sneakers. A wool coat folded on the seat. AirPods in. A hardcover novel open on the table. Relaxed, thoughtful, cosmopolitan traveler energy.",
    movement: "assis",
    tags: ["train", "voyage", "fenêtre", "paysage", "mobilité"],
  },
  {
    id: "concert_crowd",
    label: "Concert & foule",
    category: "lifestyle",
    icon: "🎵",
    setting: "Foule de concert, lumières de scène, ambiance festival",
    prompt: "Music festival or concert: standing near the front of a crowd at an outdoor festival. Behind, thousands of blurred audience members stretch back, hands raised. Stage lighting sweeps of blue, purple, and gold. A main stage structure in the distance. Confetti in the air.",
    appearance: "Subject wears festival fashion — an eclectic mix of bold pieces: fringe jacket, sequined top or graphic tee, high-waisted shorts, and chunky boots or cowboy boots. Glitter on the face, layered jewelry, temporary tattoos. Arms raised or singing along, pure joy expression.",
    movement: "statique",
    tags: ["concert", "festival", "musique", "foule", "lumières"],
  },
  {
    id: "getting_ready_vanity",
    label: "Get ready avec moi",
    category: "lifestyle",
    icon: "💄",
    setting: "Coiffeuse miroir, maquillage disposé, lumière Hollywood",
    prompt: "Beauty vanity 'get ready with me' setup: seated at a Hollywood mirror surrounded by bright warm globe lights. On the vanity: makeup palette, beauty blender, mascara, perfume bottles of various shapes, and a ring light reflection in the mirror. Fresh flowers in a bud vase.",
    appearance: "Subject wears a silk slip dress or a stylish robe in blush pink as a getting-ready outfit. Hair half-done — one half styled, the other still loose or in a clip. A makeup brush held in one hand. Building towards an elegant or glam finish look. Mascara applied on one eye.",
    movement: "assis",
    tags: ["maquillage", "beauté", "miroir", "get ready", "vanité"],
  },
  {
    id: "night_routine_bed",
    label: "Routine du soir",
    category: "lifestyle",
    icon: "🌙",
    setting: "Chambre tamisée, bougie, livre, routine nuit",
    prompt: "Calming night routine in the bedroom: seated up in bed against a pile of pillows, low ambient lighting from two warm bedside lamps. A burning scented candle on the nightstand beside a half-filled glass of water and a closed book. Curtains drawn. A phone face-down.",
    appearance: "Subject wears a cozy matching pajama set in soft cotton or silk in sage green, dusty blue, or ivory. Hair loosely braided or in a claw clip. Fresh-faced, post-skincare look with a slight glow. Holding a jade roller or reading glasses. Completely relaxed.",
    movement: "assis",
    tags: ["nuit", "chambre", "bougie", "routine", "calme"],
  },
  {
    id: "study_with_me",
    label: "Study with me",
    category: "lifestyle",
    icon: "📝",
    setting: "Bureau étudiant, livres, notes, café, concentration",
    prompt: "Student study session: seated at a desk covered with open textbooks, a ring binder, colour-coded sticky notes, a pencil case, and a ceramic coffee mug. Warm study lamp light. A whiteboard or cork board with diagrams in the blurred background.",
    appearance: "Subject wears cozy student clothing — an oversized university hoodie or a cozy earth-toned cardigan over a simple tee, with sweatpants or casual trousers. Hair pulled back with a scrunchie. Reading glasses on. A highlighter in hand. Focused, productive, studious energy.",
    movement: "assis",
    tags: ["études", "bureau", "livres", "café", "concentration"],
  },
  {
    id: "beach_walk",
    label: "Promenade plage",
    category: "lifestyle",
    icon: "👣",
    setting: "Bord de mer, promenade, vent dans les cheveux",
    prompt: "Casual beach walk: walking along the shoreline at low tide, waves gently washing over wet sand beside them. A beach town promenade with colorful beach huts in the background. Wind moves hair naturally. A beach town boardwalk visible. Bright summer light sparkling on the water.",
    appearance: "Subject wears easy beach walk attire — a flowing boho beach dress over a swimsuit, or casual linen shorts with an open short-sleeve shirt. Leather flat sandals in hand, barefoot on the wet sand. Sunglasses on. A small woven beach bag on one shoulder. Natural sun-kissed glow.",
    movement: "marche_laterale",
    tags: ["plage", "promenade", "été", "mer", "décontracté"],
  },

  // ── TRENDING FORMATS ────────────────────────────────────────────────────────

  {
    id: "unboxing_setup",
    label: "Unboxing mystère",
    category: "trending",
    icon: "📦",
    setting: "Table avec boîte mystérieuse, kraft, fond neutre",
    prompt: "Product unboxing setup: standing at a clean table covered with kraft paper. In the foreground, a matte black delivery box and tissue paper wrapping. Simple neutral off-white background. Ring light providing clean even illumination. A pair of scissors and a gift tag on the table.",
    appearance: "Subject wears clean, camera-ready casual clothing — a crisp white or neutral-coloured t-shirt or minimal sweatshirt. No busy patterns. Hair neat and styled. A slight look of excitement and anticipation. Hands positioned as if about to open the box.",
    movement: "statique",
    tags: ["unboxing", "boîte", "produit", "surprise", "ecommerce"],
  },
  {
    id: "morning_breakfast_bed",
    label: "Petit-déj au lit",
    category: "trending",
    icon: "🍳",
    setting: "Plateau petit-déj au lit, linge blanc, fleurs, œufs",
    prompt: "Breakfast in bed: seated up in a luxurious white bed with a tray containing poached eggs on sourdough, a small glass vase with fresh daisies, a French press coffee, a halved avocado, and the morning newspaper. Soft natural morning light from a bedside window.",
    appearance: "Subject wears luxurious morning attire — a premium white waffle-knit robe with the belt loosely tied, or a silk pyjama set in ivory or soft blue. Hair loosely flowing or in a half-up style. No makeup or the most natural minimal look. Stretching into a bright morning mood.",
    movement: "assis",
    tags: ["petit-déjeuner", "lit", "matin", "luxe", "fleurs"],
  },
  {
    id: "travel_vlog_landmark",
    label: "Travel vlog monument",
    category: "trending",
    icon: "🗺️",
    setting: "Devant un monument emblématique, touriste chic",
    prompt: "Travel vlog at iconic landmark: standing in front of a blurred world-famous monument — Eiffel Tower, Colosseum, or similar. Natural daylight, other tourists and local activity blurred behind. The landmark provides immediate geographic context and aspirational travel energy.",
    appearance: "Subject wears practical-chic travel clothing — a fitted bomber jacket or trench coat over a simple tee, slim comfortable trousers, and quality clean walking sneakers or boots. A compact travel camera or phone in hand. A small quality backpack. Sunglasses. Explorer confidence.",
    movement: "statique",
    tags: ["voyage", "tourisme", "monument", "vlog", "international"],
  },
  {
    id: "face_reveal_dramatic",
    label: "Face reveal dramatique",
    category: "trending",
    icon: "👁️",
    setting: "Fond neutre, éclairage split, micro-expressions",
    prompt: "Dramatic face reveal setup: standing against a deep charcoal grey seamless background. Split lighting — half the face in warm amber, half in cool blue — creating a high-contrast, dramatic portrait effect. Minimal props. Entirely focused on the subject's expression and features.",
    appearance: "Subject wears a simple, intentionally minimal outfit — a structured black turtleneck or a clean white tee that doesn't distract. Flawless minimal makeup or strong editorial makeup. Hair perfectly styled — either slicked back dramatically or a sharp blunt cut. Intense, direct gaze.",
    movement: "statique",
    tags: ["dramatic", "portrait", "éclairage", "reveal", "cinématique"],
  },
  {
    id: "cooking_kitchen_pro",
    label: "Cuisine en direct",
    category: "trending",
    icon: "👨‍🍳",
    setting: "Plan de travail pro, ingrédients, tablier, fumée",
    prompt: "Cooking content setup: standing at a professional-grade kitchen counter. Before them: a wooden cutting board with fresh herbs, a bowl of colorful vegetables, and a cast iron pan with visible steam rising. Copper pots hang on a rack above. Kitchen torch and spice jars behind.",
    appearance: "Subject wears a stylish linen chef's apron in natural or dark colour tied over a simple fitted tee and trousers. Sleeves rolled to the elbows. Hair tied back neatly. A small towel tucked into the apron strings. Confident, passionate food creator expression.",
    movement: "statique",
    tags: ["cuisine", "chef", "recette", "food", "tablier"],
  },
  {
    id: "fashion_lookbook",
    label: "Lookbook mode",
    category: "trending",
    icon: "👗",
    setting: "Fond mural texturé, pose mode, lumière studio",
    prompt: "Fashion lookbook shoot: standing against a textured raw concrete or limewash plaster wall, lit by a large overhead softbox creating soft diffused studio light. A coat rack with garments visible at frame edge. Floor markings suggesting a real fashion shoot.",
    appearance: "Subject wears an intentional fashion-forward outfit — the key statement piece of the collection, styled precisely: structured shoulders, interesting silhouette, coordinated shoes and accessories. Everything deliberate. Editorial hair and makeup. Poses as a professional model.",
    movement: "demi_tour",
    tags: ["mode", "fashion", "lookbook", "éditorial", "studio"],
  },
];

// Unique categories with counts (for UI filter tabs)
export const UGC_CATEGORIES = [
  { id: "all", label: "Tous", icon: "✨" },
  { id: "studio", label: "Studio", icon: "🎙️" },
  { id: "home", label: "Intérieur", icon: "🏠" },
  { id: "cafe", label: "Café & Resto", icon: "☕" },
  { id: "street", label: "Rue & Urbain", icon: "🏙️" },
  { id: "nature", label: "Nature", icon: "🌿" },
  { id: "premium", label: "Premium", icon: "⭐" },
  { id: "lifestyle", label: "Lifestyle", icon: "✈️" },
  { id: "trending", label: "Trending", icon: "🔥" },
] as const;

/**
 * Builds the full generation prompt from a selected UGC format.
 * Combines the scene description with the avatar appearance so the model
 * generates a character that visually belongs in the scene.
 */
export function buildFormatPrompt(format: UGCFormat): string {
  return `${format.prompt}\n\nSubject appearance: ${format.appearance}`;
}
